var UpcomingMovies = require("../models/upcoming_movies");

new UpcomingMovies({tmdb_id: "195589",
imdb_id: "tt2004420",
genres : ["Comedy"],
title: "Neighbors",
directors : ["Nicholas Stoller"],
actors : ["Seth Rogen", "Zac Efron", "Rose Byrne", "Dave Franco", "Christopher Mintz-Plasse", "Jake Johnson", "Lisa Kudrow", "Carla Gallo", "Ali Corbin", "Chasty Ballesteros", "Halston Sage", "Cassandra Starr", "Bobby Moynihan", "Craig Roberts", "Jesse Heiman", "Hannibal Buress", "Jason Mantzoukas", "Ike Barinholtz", "Ali Cobrin", "Natasha Leggero"],
trailer: "http://youtube.com/watch?v=vP9QCAcGy7Y",
url: "http://trakt.tv/movie/neighbors-2014",
tagline: "Family vs. Frat",
overview: "A couple with a newborn baby face unexpected difficulties after they are forced to live next to a fraternity house.",
poster: "http://slurm.trakt.us/images/posters_movies/221641.3.jpg",
release_date: "1399618800"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "198663",
imdb_id: "tt1790864",
genres : ["Mystery", "Science Fiction", "Thriller"],
title: "The Maze Runner",
directors : ["Steve Gehrke", "Wes Ball"],
actors : ["Will Poulter", "Dylan OBrien", "Thomas Sangster", "Kaya Scodelario", "Patricia Clarkson", "Ki Hong Lee", "Jacob Latimore", "Aml Ameen", "Chris Sheffield", "Joe Adler", "Don McManus", "Dexter Darden"],
trailer: "http://youtube.com/watch?v=vnq3z9o1xro",
url: "http://trakt.tv/movie/the-maze-runner-2014",
tagline: "",
overview: "Set in a post-apocalyptic world, young Thomas is deposited in a community of boys after his memory is erased, soon learning theyre all trapped in a maze that will require him to join forces with fellow runners for a shot at escape.",
poster: "http://slurm.trakt.us/images/posters_movies/219176.1.jpg",
release_date: "1411110000"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "254474",
imdb_id: "tt2784512",
genres : [],
title: "Zombeavers",
directors : ["Jordan Rubin", "Sarah Schultz"],
actors : ["Rachel Melvin", "Cortney Palm", "Lexi Atkins", "Hutch Dano", "Jake Weary", "Rex Linn", "Brent Briscoe", "Phyllis Katz", "Bill Burr", "John Mayer"],
trailer: "http://youtube.com/watch?v=7onFrBK_hKE",
url: "http://trakt.tv/movie/zombeavers-2014",
tagline: "Youll be dammed!",
overview: "ZOMBEAVERS is an action-packed horror/comedy in which a group of college kids staying at a riverside cabin are menaced by a swarm of deadly zombie beavers. A weekend of sex and debauchery soon turns gruesome as the beavers close in on the kids. Riding the line between scary, sexy and funny, the kids are soon fighting for their lives in a desperate attempt to fend off the hoard of beavers that attack them in and around their cabin.",
poster: "http://slurm.trakt.us/images/posters_movies/228425.jpg",
release_date: "1397890800"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "152601",
imdb_id: "tt1798709",
genres : ["Comedy", "Science Fiction", "Romance", "Drama"],
title: "Her",
directors : ["Spike Jonze"],
actors : ["Joaquin Phoenix", "Scarlett Johansson", "Rooney Mara", "Amy Adams", "Olivia Wilde", "Samantha Morton", "Chris Pratt", "Portia Doubleday", "Sam Jaeger", "Katherine Boecher", "Kelly Sarah", "Spike Jonze", "Bill Hader", "Kristen Wiig", "Brian Cox"],
trailer: "http://youtube.com/watch?v=WzV6mXIOVl4",
url: "http://trakt.tv/movie/her-2013",
tagline: "A Spike Jonze Love Story",
overview: "In the not so distant future, Theodore, a lonely writer purchases a newly developed operating system designed to meet the users every needs. To Theordores surprise, a romantic relationship develops between him and his operating system. This unconventional love story blends science fiction and romance in a sweet tale that explores the nature of love and the ways that technology isolates and connects us all.",
poster: "http://slurm.trakt.us/images/posters_movies/211688.5.jpg",
release_date: "1387353600"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "149509",
imdb_id: "tt1528071",
genres : ["Drama", "Fantasy", "Horror"],
title: "Horns",
directors : ["Alexandre Aja"],
actors : ["Daniel Radcliffe", "Juno Temple", "Kelli Garner", "James Remar", "Max Minghella", "Joe Anderson", "Sabrina Carpenter", "Laine MacNeil", "Dylan Schmid"],
trailer: "http://youtube.com/watch?v=B8s_1UcdoNI",
url: "http://trakt.tv/movie/horns-2014",
tagline: "He Will Bring Out The Devil In You",
overview: "In the aftermath of his girlfriends mysterious death, a young man awakens to strange horns sprouting from his temples.",
poster: "http://slurm.trakt.us/images/posters_movies/215361.1.jpg",
release_date: "1412319600"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "290336",
imdb_id: "tt2208568",
genres : [],
title: "Montana",
directors : ["Mo Ali"],
actors : ["Michelle Fairley", "Lars Mikkelsen", "Ashley Walters", "Zlatko Buric", "Adam Deacon", "Alexandra Weaver", "Dominique Tipper", "Ryan Oliva", "Sinead Michael", "Clint Dyer", "Kedar Williams-Stirling", "Oliver Stark", "Rocky Marshall"],
trailer: "http://youtube.com/watch?v=rBjtBIrYYUQ",
url: "http://trakt.tv/movie/montana-2014",
tagline: "Raised in the streets, trained by an assassin.",
overview: "In the mean streets of Londons East End, a former Serbian commando and a fourteen-year old boy plot revenge against a powerful crime lord and his ruthless lieutenants. As our heroes prepare to take on their enemies, the boy is mentored in the dark arts of assassination and learns the true meaning of friendship, honor and respect.",
poster: "http://slurm.trakt.us/images/posters_movies/239970.jpg",
release_date: "1418630400"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "3114",
imdb_id: "tt0049730",
genres : ["Western"],
title: "The Searchers",
directors : ["John Ford"],
actors : ["John Wayne", "Jeffrey Hunter", "Vera Miles", "Natalie Wood", "Ward Bond", "John Qualen", "Olive Carey", "Henry Brandon", "Ken Curtis", "Harry Carey Jr.", "Antonio Moreno", "Hank Worden", "Beulah Archuletta", "Walter Coy", "Dorothy Jordan", "Pippa Scott", "Patrick Wayne", "Lana Wood"],
trailer: "http://youtube.com/watch?v=SlWT8kTccHw",
url: "http://trakt.tv/movie/the-searchers-1956",
tagline: "He had to find her... he had to find her...",
overview: "As a Civil War veteran spends years searching for a young niece captured by Indians, his motivation becomes increasingly questionable.",
poster: "http://slurm.trakt.us/images/posters_movies/7758.jpg",
release_date: "-435600000"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "238636",
imdb_id: "tt2975578",
genres : ["Horror", "Thriller"],
title: "The Purge: Anarchy",
directors : ["James DeMonaco"],
actors : ["Frank Grillo", "Carmen Ejogo", "Zach Gilford", "Kiele Sanchez", "Zoe Borde", "Justina Machado", "John Beasley", "Jack Conley", "Noel Gugliemi", "Castulo Guerra", "Michael K. Williams", "Zoe Soul", "Edwin Hodge", "Keith Stanfield", "Roberta Valderrama", "Amy Paffrath", "Niko Nicotera", "Cortney Palm", "Judith McConnell", "Chad Morgan", "Bel Hernandez", "Lily Knight", "Jasper Cole", "Brandon Keener", "Amy Price-Francis", "Matt Lasky", "Nicholas Gonzalez", "Adrian Sparks"],
trailer: "http://youtube.com/watch?v=XzFCDqKE4yA",
url: "http://trakt.tv/movie/the-purge-anarchy-2014",
tagline: "",
overview: "Sequel to The Purge. The New Founders of America invite you to celebrate your annual right to Purge. The Purge: Anarchy, the sequel to summer 2013s sleeper hit that opened to No. 1 at the box-office, sees the return of writer/director James DeMonaco to craft the next terrifying chapter of dutiful citizens preparing for their countrys yearly 12 hours of anarchy.",
poster: "http://slurm.trakt.us/images/posters_movies/225722.1.jpg",
release_date: "1405580400"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "131631",
imdb_id: "tt1951265",
genres : ["Adventure", "Science Fiction", "Thriller"],
title: "The Hunger Games: Mockingjay - Part 1",
directors : ["Francis Lawrence"],
actors : ["Jennifer Lawrence", "Josh Hutcherson", "Liam Hemsworth", "Woody Harrelson", "Robert Knepper", "Sam Claflin", "Julianne Moore", "Lily Rabe", "Evan Ross", "Philip Seymour Hoffman", "Elden Henson", "Stef Dawson", "Mahershala Ali", "Wes Chatham"],
trailer: "http://youtube.com/watch?v=7dCB2U9lX48",
url: "http://trakt.tv/movie/the-hunger-games-mockingjay-part-1-2014",
tagline: "",
overview: "Katniss Everdeen reluctantly becomes the symbol of a mass rebellion against the autocratic Capitol.",
poster: "http://slurm.trakt.us/images/posters_movies/205963.1.jpg",
release_date: "1416556800"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "101299",
imdb_id: "tt1951264",
genres : ["Science Fiction", "Thriller", "Action", "Adventure"],
title: "The Hunger Games: Catching Fire",
directors : ["Francis Lawrence"],
actors : ["Jennifer Lawrence", "Josh Hutcherson", "Sam Claflin", "Elizabeth Banks", "Alan Ritchson", "Jena Malone", "Stanley Tucci", "Willow Shields", "Woody Harrelson", "Philip Seymour Hoffman", "Donald Sutherland", "Amanda Plummer", "Meta Golding", "Lenny Kravitz", "Lynn Cohen", "Toby Jones", "Stephanie Leigh Schlund", "Bruno Gunn", "Maria Howell", "E. Roger Mitchell", "Patrick St. Esprit", "Liam Hemsworth"],
trailer: "http://youtube.com/watch?v=jyPnQw_Lqds",
url: "http://trakt.tv/movie/the-hunger-games-catching-fire-2013",
tagline: "Every revolution begins with a spark.",
overview: "Katniss Everdeen has returned home safe after winning the 74th Annual Hunger Games along with fellow tribute Peeta Mellark. Winning means that they must turn around and leave their family and close friends, embarking on a Victors Tour of the districts. Along the way Katniss senses that a rebellion is simmering, but the Capitol is still very much in control as President Snow prepares the 75th Annual Hunger Games (The Quarter Quell) - a competition that could change Panem forever.",
poster: "http://slurm.trakt.us/images/posters_movies/203028.3.jpg",
release_date: "1385107200"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "118340",
imdb_id: "tt2015381",
genres : ["Science Fiction", "Fantasy", "Adventure"],
title: "Guardians of the Galaxy",
directors : ["James Gunn"],
actors : ["Chris Pratt", "Zoe Saldana", "Dave Bautista", "Vin Diesel", "Bradley Cooper", "Damion Poitier", "Lee Pace", "Michael Rooker", "Karen Gillan", "Djimon Hounsou", "John C. Reilly", "Glenn Close", "Benicio Del Toro", "Laura Haddock", "Ophelia Lovibond", "Sean Gunn", "Peter Serafinowicz", "Gregg Henry", "Stan Lee", "Lloyd Kaufman", "Nathan Fillion", "Alexis Denisof", "Rob Zombie", "James Gunn", "Tyler Bates", "Josh Brolin", "Seth Green"],
trailer: "http://youtube.com/watch?v=XT4CLuTbI7A",
url: "http://trakt.tv/movie/guardians-of-the-galaxy-2014",
tagline: "All heroes start somewhere.",
overview: "Light years from Earth, 26 years after being abducted, Peter Quill finds himself the prime target of a manhunt after discovering an orb wanted by Ronan the Accuser.",
poster: "http://slurm.trakt.us/images/posters_movies/203046.2.jpg",
release_date: "1406876400"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "270946",
imdb_id: "tt1911658",
genres : [],
title: "Penguins of Madagascar",
directors : ["Simon J. Smith"],
actors : ["Ben Stiller", "Benedict Cumberbatch", "Jada Pinkett Smith", "David Schwimmer", "John Malkovich", "Chris Rock", "Peter Stormare", "John DiMaggio", "Ken Jeong", "Annet Mahendru", "Nicole Sullivan", "Cedric the Entertainer", "Andy Richter", "Tom McGrath", "Chris Miller", "Christopher Knights"],
trailer: "http://youtube.com/watch?v=KHGHEpUeUwo",
url: "http://trakt.tv/movie/penguins-of-madagascar-2014",
tagline: "",
overview: "Featuring the beloved penguins from Dreamworks Madagascar franchise.",
poster: "http://slurm.trakt.us/images/posters_movies/219819.jpg",
release_date: "1416988800"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "241254",
imdb_id: "tt1085492",
genres : ["Action", "Thriller"],
title: "The Prince",
directors : ["Brian A. Miller"],
actors : ["Bruce Willis", "Jason Patric", "John Cusack", "Jessica Lowndes", "Gia Mantegna", "Rain", "50 Cent", "Don Harvey", "Jesse Pruett", "Didi Costine", "Bonnie Somerville", "Tim Fields", "Jonathon Schaech", "Andrea Burns", "Jim Bennett"],
trailer: "http://youtube.com/watch?v=uMNKLvD2F1k",
url: "http://trakt.tv/movie/the-prince-2014",
tagline: "Mercy is for the Weak",
overview: "A family man who turns out to be a retired mob enforcer must travel across the country to find his daughter who has gone missing.",
poster: "http://slurm.trakt.us/images/posters_movies/236097.1.jpg",
release_date: "1408690800"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "266856",
imdb_id: "tt2980516",
genres : ["Drama"],
title: "The Theory of Everything",
directors : ["James Marsh"],
actors : ["Felicity Jones", "Emily Watson", "Harry Lloyd", "David Thewlis", "Charlotte Hope", "Adam Godley", "Lesley Manville", "Maxine Peake", "Eddie Redmayne"],
trailer: "http://youtube.com/watch?v=1YjF5gV_Tc4",
url: "http://trakt.tv/movie/the-theory-of-everything-2014",
tagline: "",
overview: "A look at the relationship between the famous physicist Stephen Hawking and his wife.",
poster: "http://slurm.trakt.us/images/posters_movies/232738.jpg",
release_date: "1415347200"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "204922",
imdb_id: "tt1726592",
genres : [],
title: "Before I Go to Sleep",
directors : ["Rowan Joffe"],
actors : ["Nicole Kidman", "Colin Firth", "Mark Strong", "Anne-Marie Duff", "Jing Lusi", "Dean-Charles Chapman"],
trailer: "http://youtube.com/watch?v=ag1tQ31nW40",
url: "http://trakt.tv/movie/before-i-go-to-sleep-2014",
tagline: "",
overview: "A woman wakes up every day, remembering nothing as a result of a traumatic accident in her past. One day, new terrifying truths emerge that force her to question everyone around her.",
poster: "http://slurm.trakt.us/images/posters_movies/229484.jpg",
release_date: "1414738800"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "265851",
imdb_id: "tt3697566",
genres : ["Action", "Thriller"],
title: "No Tears for the Dead",
directors : ["Jeong-beom Lee"],
actors : ["Dong-gun Jang", "Minhee Kim", "Kang Han-Na", "Hee-won Kim", "Brian Tee", "Kim Joon-Sung", "Byun Yo-Han", "Min-hie Kim"],
trailer: "http://youtube.com/watch?v=ulv5ICaMo6Y",
url: "http://trakt.tv/movie/no-tears-for-the-dead-2014",
tagline: "",
overview: "Abandoned by his mother shortly after immigrating to America, Gon is raised by the mafia and grows up to become a cold-blooded hitman. Though usually flawless in taking out his targets, Gon makes a terrible mistake of killing an innocent young girl. Swamped by feelings of regret, guilt and shame, Gon no longer wants to be a hitman, but his boss gives him one last mission. So Gon finds himself in Korea, the land of the mother that abandoned him, on the trail of his last target. But in bitter irony, that target is Mo-gyeong, the mother of the dead child.",
poster: "http://slurm.trakt.us/images/posters_movies/235457.jpg",
release_date: "1401606000"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "245891",
imdb_id: "tt2911666",
genres : ["Action", "Thriller"],
title: "John Wick",
directors : ["Chad Stahelski", "David Leitch"],
actors : ["Keanu Reeves", "Adrianne Palicki", "Bridget Regan", "Willem Dafoe", "Bridget Moynahan", "Jason Isaacs", "Alfie Allen", "Omer Barnea", "Lance Reddick", "Toby Leonard Moore"],
trailer: "http://youtube.com/watch?v=RllJtOw0USI",
url: "http://trakt.tv/movie/john-wick-2014",
tagline: "Dont set him off.",
overview: "A former hit man is pursued by an old friend who was contracted to kill him.",
poster: "http://slurm.trakt.us/images/posters_movies/238646.1.jpg",
release_date: "1414134000"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "289416",
imdb_id: "tt3068192",
genres : ["Horror", "Thriller"],
title: "Grace: The Possession",
directors : ["Jeff Chan"],
actors : ["Alexia Fast", "Joel Moore", "Lin Shaye", "Brett Dier", "John Emmett Tracy", "Daniel Arnold"],
trailer: "http://youtube.com/watch?v=ijkk9itwpsQ",
url: "http://trakt.tv/movie/grace-the-possession-2014",
tagline: "Innocence ends in blood",
overview: "A unique horror film told from the first-person perspective of Grace - a naive, virginal college freshman trying to deal with campus culture and her outgoing roommate as an evil entity takes over her body and unleashes chaos.",
poster: "http://slurm.trakt.us/images/posters_movies/242619.jpg",
release_date: "1414479600"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "187017",
imdb_id: "tt2294449",
genres : ["Action", "Comedy", "Crime"],
title: "22 Jump Street",
directors : ["Chris Miller", "Phil Lord"],
actors : ["Jonah Hill", "Channing Tatum", "Dave Franco", "Ice Cube", "Nick Offerman", "Peter Stormare", "Rob Riggle", "Wyatt Russell", "Richard Grieco", "Amber Stevens", "Jillian Bell", "Jimmy Tatro", "Caroline Aaron", "Joe Chrest", "Marc Evan Jackson", "Eddie J. Fernandez", "Dax Flame", "Johnny Pemberton", "Anna Faris", "Bill Hader", "Patton Oswalt", "Seth Rogen", "Queen Latifah", "Dustin Nguyen"],
trailer: "http://youtube.com/watch?v=i3_gKCX4Cik",
url: "http://trakt.tv/movie/22-jump-street-2014",
tagline: "Theyre not 21 anymore",
overview: "After making their way through high school (twice), big changes are in store for officers Schmidt and Jenko when they go deep undercover at a local college. But when Jenko meets a kindred spirit on the football team, and Schmidt infiltrates the bohemian art major scene, they begin to question their partnership. Now they dont have to just crack the case - they have to figure out if they can have a mature relationship. If these two overgrown adolescents can grow from freshmen into real men, college might be the best thing that ever happened to them.",
poster: "http://slurm.trakt.us/images/posters_movies/217179.3.jpg",
release_date: "1402642800"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "210577",
imdb_id: "tt2267998",
genres : ["Thriller", "Drama", "Mystery"],
title: "Gone Girl",
directors : ["David Fincher"],
actors : ["Ben Affleck", "Rosamund Pike", "Tyler Perry", "Neil Patrick Harris", "Missi Pyle", "Patrick Fugit", "Kim Dickens", "Casey Wilson", "Kathleen Rose Perkins", "Emily Ratajkowski", "Scoot McNairy", "Boyd Holbrook", "Carrie Coon"],
trailer: "http://youtube.com/watch?v=2OSgeD7k6I0",
url: "http://trakt.tv/movie/gone-girl-2014",
tagline: "You dont know what youve got til its...",
overview: "With his wifes disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when its suspected that he may not be innocent.",
poster: "http://slurm.trakt.us/images/posters_movies/223619.4.jpg",
release_date: "1412319600"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "106646",
imdb_id: "tt0993846",
genres : ["Crime", "Drama", "Comedy"],
title: "The Wolf of Wall Street",
directors : ["Martin Scorsese"],
actors : ["Leonardo DiCaprio", "Jonah Hill", "Margot Robbie", "Kyle Chandler", "Rob Reiner", "Matthew McConaughey", "Jon Bernthal", "Kenneth Choi", "P. J. Byrne", "Brian Sacca", "Henry Zebrowski", "Jon Favreau", "Cristin Milioti", "Joanna Lumley", "Shea Whigham", "Jake Hoffman", "Spike Jonze", "Ethan Suplee", "Madison McKinley", "Jean Dujardin", "Katarina Cas", "Ashley Blankenship", "Christine Ebersole", "Nicole Rutigliano", "P.J. Byrne", "Chris Riggi"],
trailer: "http://youtube.com/watch?v=iszwuX1AK6A",
url: "http://trakt.tv/movie/the-wolf-of-wall-street-2013",
tagline: "EARN. SPEND. PARTY.",
overview: "A New York stockbroker refuses to cooperate in a large securities fraud case involving corruption on Wall Street, corporate banking world and mob infiltration. Based on Jordan Belforts autobiography.",
poster: "http://slurm.trakt.us/images/posters_movies/209707.4.jpg",
release_date: "1387958400"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "231576",
imdb_id: "tt2870708",
genres : ["Comedy", "Drama"],
title: "Wish I Was Here",
directors : ["Zach Braff"],
actors : ["Zach Braff", "Kate Hudson", "Joey King", "Pierce Gagnon", "Donald Faison", "Mandy Patinkin", "Ashley Greene", "Jim Parsons", "James Avery", "Alexander Chaplin", "Josh Gad"],
trailer: "http://youtube.com/watch?v=kw8VCDx399I",
url: "http://trakt.tv/movie/wish-i-was-here-2014",
tagline: "Life is an occasion. Rise to it.",
overview: "Aidan Bloom, a struggling actor, father and husband, is 35 years old and still trying to find a purpose for his life. He and his wife are barely getting by financially and Aidan passes his time by fantasizing about being the great futuristic Space-Knight hed always dreamed hed be as a little kid. When his ailing father can no longer afford to pay for private school for his two kids and the only available public school is on its last legs, Aidan reluctantly agrees to attempt to home-school them. Through teaching them about life his way, Aidan gradually discovers some of the parts of himself he couldnt find.",
poster: "http://slurm.trakt.us/images/posters_movies/226018.jpg",
release_date: "1390032000"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "119450",
imdb_id: "tt2103281",
genres : ["Action", "Drama", "Science Fiction", "Thriller"],
title: "Dawn of the Planet of the Apes",
directors : ["Matt Reeves", "Rupert Wyatt"],
actors : ["Andy Serkis", "Judy Greer", "Terry Notary", "Gary Oldman", "Keri Russell", "Jason Clarke", "Kodi Smit-McPhee", "Karin Konoval", "Kirk Acevedo", "Richard King", "Lucky Johnson", "Jocko Sims"],
trailer: "http://youtube.com/watch?v=3wMnftb_RI4",
url: "http://trakt.tv/movie/dawn-of-the-planet-of-the-apes-2014",
tagline: "One last chance for peace.",
overview: "A group of scientists in San Francisco struggle to stay alive in the aftermath of a plague that is wiping out humanity, while Caesar tries to maintain dominance over his community of intelligent apes.",
poster: "http://slurm.trakt.us/images/posters_movies/211624.4.jpg",
release_date: "1405062000"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "155",
imdb_id: "tt0468569",
genres : ["Action", "Drama", "Crime", "Thriller"],
title: "The Dark Knight",
directors : ["Christopher Nolan"],
actors : ["Christian Bale", "Heath Ledger", "Aaron Eckhart", "Michael Caine", "Maggie Gyllenhaal", "Gary Oldman", "Morgan Freeman", "Ron Dean", "Cillian Murphy", "Michael Jai White", "Chin Han", "James Smith", "Monique Gabriela Curnen", "Nestor Carbonell", "Eric Roberts", "Ritchie Coster", "Anthony Michael Hall", "Keith Szarabajka", "Colin McFarlane", "Melinda McGraw", "William Fichtner", "David Dastmalchian", "Edison Chen", "Danny Goldring", "Joshua Harto", "Michael Stoyanov", "Beatrice Rosen", "Nathan Gamble", "Matthew Leitch", "Michael Vieau", "William Smillie", "Matthew ONeill", "Olumiji Olawumi", "Greg Beam", "Erik Hellman", "Vincenzo Nicoli", "Nydia Rodriguez Terracina", "Andy Luther", "James Farruggio", "Tom McElroy", "Will Zahrn", "James Fierro", "Patrick Leahy", "Sam Derence", "Jennifer Knox", "Patrick Clear", "Sarah Jayne Dunn", "Charles Venn", "Winston Ellis", "Sophia Hinshelwood", "Keith Kupferer", "Joseph Luis Caballero", "Richard Dillane", "Daryl Satcher", "Chris Petschler", "Aidan Feore", "Philip Bulcock", "Paul Birchard", "Walter Lewis", "Vincent Riotta", "Nancy Crane", "K. Todd Freeman", "Matt Shallenberger", "Michael Andrew Gorman", "Lanny Lutz", "Peter Defaria", "Matt Rippy", "Andrew Bicknell", "Ariyon Bakare", "Doug Ballard", "Helene Wilson", "Tommy Campbell", "Craig Heaney", "Lorna Gayle", "Lisa McAllister", "Peter Brooke", "Joshua Rollins", "Dale Rivera", "Tommy Tiny Lister", "Thomas Gaitsch", "William Armstrong", "Adam Kalesperis", "Tristan Tait", "Bronson Webb", "David Ajala", "Gertrude Mosley", "Jonathan Ryland", "James Scales", "Nigel Carrington", "Ian Pirie", "Lateef Lovejoy", "Grahame Edwards", "Roger Monk", "Ronan Summers", "Wai Wong", "Michael Corey Foster", "Hannah Gunn", "Brandon Lambdin", "Jeff Albertson", "Tracy L. Aldaz", "Matthew W. Allen", "Stephen Armourae", "Mike Bach", "Wayne Baker", "Martin Ballantyne", "Tommy Bartlett", "Blayne Bennett", "Jon Lee Brody", "Debbi Burns", "Maritza Cabrera", "Laura Chernicky", "Matt Cho", "Henry Milton Chu", "Kelli Clevenger", "Bruce Allen Dawson", "Danielle Day", "Richard Divizio", "Tony Domino", "Jessica Doyle", "David William James Elliott", "Gene Fojtik", "Reese Foster", "Jason Frederick", "Darren Elliot Fulsher", "David Fultz", "Scott Ganyo", "Marisol Giraud"],
trailer: "http://youtube.com/watch?v=GVx5K8WfFJY",
url: "http://trakt.tv/movie/the-dark-knight-2008",
tagline: "Why So Serious?",
overview: "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
poster: "http://slurm.trakt.us/images/posters_movies/448.4.jpg",
release_date: "1216364400"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "64688",
imdb_id: "tt1232829",
genres : ["Action", "Comedy", "Crime"],
title: "21 Jump Street",
directors : ["Chris Miller", "Phil Lord"],
actors : ["Channing Tatum", "Jonah Hill", "Brie Larson", "Ellie Kemper", "Ice Cube", "Dave Franco", "Nick Offerman", "Lindsey Broad", "Rob Riggle", "Johnny Depp", "Jake Johnson", "Holly Robinson Peete", "Johnny Pemberton", "Caroline Aaron", "Joe Chrest", "Dakota Johnson", "Johnny Simmons"],
trailer: "http://youtube.com/watch?v=ISJR4rVO0TQ",
url: "http://trakt.tv/movie/21-jump-street-2012",
tagline: "They thought the streets were mean. Then they went back to high school.",
overview: "In high school, Schmidt was a dork and Jenko was the popular jock. After graduation, both of them joined the police force and ended up as partners riding bicycles in the city park. Since they are young and look like high school students, they are assigned to an undercover unit to infiltrate a drug ring that is supplying high school students synthetic drugs.",
poster: "http://slurm.trakt.us/images/posters_movies/181508.3.jpg",
release_date: "1331535600"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "91314",
imdb_id: "tt2109248",
genres : ["Science Fiction", "Action", "Adventure"],
title: "Transformers: Age of Extinction",
directors : ["Michael Bay"],
actors : ["Mark Wahlberg", "Stanley Tucci", "Nicola Peltz", "Jack Reynor", "Bingbing Li", "Frank Welker", "Miguel Ferrer", "Jeffrey Combs", "Mark Rolston", "Sophia Myles", "Titus Welliver", "Peter Cullen", "John Goodman", "Ken Watanabe", "Kelsey Grammer", "Geng Han"],
trailer: "http://youtube.com/watch?v=EOmpqg1YoWU",
url: "http://trakt.tv/movie/transformers-age-of-extinction-2014",
tagline: "This is not war. Its extinction.",
overview: "As humanity picks up the pieces, following the conclusion of Transformers: Dark of the Moon, Autobots and Decepticons have all but vanished from the face of the planet. However, a group of powerful, ingenious businessman and scientists attempt to learn from past Transformer incursions and push the boundaries of technology beyond what they can control - all while an ancient, powerful Transformer menace sets Earth in his cross-hairs.",
poster: "http://slurm.trakt.us/images/posters_movies/194709.1.jpg",
release_date: "1403852400"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "301748",
imdb_id: "tt2796678",
genres : ["Comedy"],
title: "Opposite Sex",
directors : ["Jennifer Finnigan", "Jonathan Silverman"],
actors : ["Mena Suvari", "Eric Roberts", "Kristin Chenoweth", "Dana Ashbrook", "Kenan Thompson", "Jennifer Finnigan"],
trailer: "http://youtube.com/watch?v=fR4COuXHFdg",
url: "http://trakt.tv/movie/opposite-sex-2014",
tagline: "A battle of the sexes, winner takes all.",
overview: "A Bets A Bet tells the story of Vince, New Englands most successful divorce attorney. To Vince, life is one big competition, and losing is unacceptable. This also applies in his dating life with his love em and leave em approach. Then Vince meets Jane, who is beautiful, successful and also extremely driven. Together they enter into a series of entertaining wagers with each other where the winner gets to decide the fate of the loser. After all, A Bets a Bet!",
poster: "http://slurm.trakt.us/images/posters_movies/243263.jpg",
release_date: "1415433600"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "45243",
imdb_id: "tt1411697",
genres : ["Comedy"],
title: "The Hangover Part II",
directors : ["Todd Phillips"],
actors : ["Bradley Cooper", "Zach Galifianakis", "Justin Bartha", "Ed Helms", "Juliette Lewis", "Ken Jeong", "Mike Tyson", "Jamie Chung", "Paul Giamatti", "Bill Clinton", "Jeffrey Tambor", "Liam Neeson", "Mason Lee", "Sasha Barrese", "Gillian Vigman", "Aroon Seeboonruang", "Nirut Sirichanya", "Yasmin Lee", "Nick Cassavetes", "Sondra Currie", "Bryan Callen", "Brody Stevens", "Michael Berry Jr.", "Andrew Howard", "Penpak Sirikul"],
trailer: "http://youtube.com/watch?v=9xXBjtAGIzE",
url: "http://trakt.tv/movie/the-hangover-part-ii-2011",
tagline: "The wolfpack is back.",
overview: "The Hangover crew heads to Thailand for Stus wedding. After the disaster of a bachelor party in Las Vegas last year, Stu is playing it safe with a mellow pre-wedding brunch. However, nothing goes as planned and Bangkok is the perfect setting for another adventure with the rowdy group.",
poster: "http://slurm.trakt.us/images/posters_movies/12282.1.jpg",
release_date: "1306306800"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "189",
imdb_id: "tt0458481",
genres : ["Action", "Drama", "Thriller"],
title: "Sin City: A Dame to Kill For",
directors : ["Frank Miller", "Robert Rodriguez"],
actors : ["Mickey Rourke", "Jessica Alba", "Clive Owen", "Josh Brolin", "Joseph Gordon-Levitt", "Rosario Dawson", "Bruce Willis", "Devon Aoki", "Michael Madsen", "Danny Trejo", "Eva Green", "Michael Clarke Duncan", "Powers Boothe", "Dennis Haysbert", "Ray Liotta", "Christopher Meloni", "Jeremy Piven", "Christopher Lloyd", "Jaime King", "Juno Temple", "Stacy Keach", "Marton Csokas", "Jude Ciccolella", "Jamie Chung", "Julia Garner", "Lady Gaga", "Alexa Vega", "Crystal McCahill"],
trailer: "http://youtube.com/watch?v=Bmhy9VYVY8c",
url: "http://trakt.tv/movie/sin-city-a-dame-to-kill-for-2014",
tagline: "There is no justice without sin.",
overview: "Some of Sin Citys most hard-boiled citizens cross paths with a few of its more reviled inhabitants.",
poster: "http://slurm.trakt.us/images/posters_movies/176746.2.jpg",
release_date: "1408690800"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "100042",
imdb_id: "tt2096672",
genres : ["Comedy"],
title: "Dumb and Dumber To",
directors : ["Bobby Farrelly", "Peter Farrelly"],
actors : ["Jim Carrey", "Jeff Daniels", "Rachel Melvin", "Kathleen Turner", "Brady Bluhm", "Laurie Holden", "Steve Tom", "Rob Riggle", "Jennifer Lawrence", "Gregory Fears", "Eddie Shin", "Atkins Estimonds", "Lindsay Ayliffe", "Matthew Cardarople", "Tim Campione", "Jennifer Cocker", "Derrick Dean", "Garret H. Dumas", "Shelton Foreman", "Jeff Matthew Glover", "Walter Hendrix III", "Lauren Henneberg", "Michael Jaegers", "Aaron Kischnick", "Rob Koebel", "Taylor McPherson", "David Pascua", "William R. Phillips", "Josh Turner", "Stefan Walker Armstrong", "Walt Arnett", "Paul Bednarz", "Erika Bierman", "Derek Blankenship", "Kassidy Claire", "Jesse Clark", "Bryan Dilbeck", "Joe Foley", "Abigail Gamache", "Dalton E. Gray", "Llauryn P. Hendrix", "Ron Hudson", "Kathlene Huslin", "Erick Reihs Jackson", "Darien Johnson", "Jeffrey Karantza", "Debi Kimsey", "Anthony R. McClara", "Michael McCrudden", "Richard Melton", "Maia Moss-Fife", "Ryan Nesset", "Orbert Rogers", "Sade Shearer", "Dereck Smith", "Jeff Sumner", "Dave Walpole", "Christina Michelle Williams", "Brett Wyman", "Doris Dean", "John Deifer", "Jacklyn Edney", "David Emmett", "Cody Mark Hanna", "Billy Boy Johnson", "John Merical", "Barbara Prince"],
trailer: "http://youtube.com/watch?v=bIqvQFqPavA",
url: "http://trakt.tv/movie/dumb-and-dumber-to-2014",
tagline: "",
overview: "20 years after the dimwits set out on their first adventure, they head out in search of one of their long lost children in the hope of gaining a new kidney.",
poster: "http://slurm.trakt.us/images/posters_movies/211629.jpg",
release_date: "1415952000"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "218836",
imdb_id: "tt2980706",
genres : ["Animation", "Comedy", "Adventure", "Family"],
title: "Planes: Fire & Rescue",
directors : ["Roberts Gannaway"],
actors : ["Dane Cook", "Ed Harris", "Julie Bowen", "Curtis Armstrong", "John Michael Higgins", "Hal Holbrook", "Wes Studi", "Brad Garrett", "Teri Hatcher", "Stacy Keach", "Cedric the Entertainer", "Danny Mann", "Barry Corbin", "Regina King", "Anne Meara", "Jerry Stiller", "Fred Willard", "Dale Dye", "Matt L. Jones", "Bryan Callen", "Danny Pardo", "Corri English", "Kari Wahlgren", "Patrick Warburton", "Rene Auberjonois", "Erik Estrada", "Steve Schirripa", "Brent Musburger", "John Ratzenberger", "Caroline Aaron", "Ferrell Barron", "Roberts Gannaway", "Kate Micucci", "Masasa Moyo", "Brad Paisley", "Fred Tatasciore"],
trailer: "http://youtube.com/watch?v=Uk0D5L0TT30",
url: "http://trakt.tv/movie/planes-fire-and-rescue-2014",
tagline: "When others fly out, heroes fly in.",
overview: "When world-famous air racer Dusty learns that his engine is damaged and he may never race again, he must shift gears and is launched into the world of aerial firefighting. Dusty joins forces with veteran fire and rescue helicopter Blade Ranger and his team, a bunch of all-terrain vehicles known as The Smokejumpers. Together, the fearless team battles a massive wildfire, and Dusty learns what it takes to become a true hero.",
poster: "http://slurm.trakt.us/images/posters_movies/222814.2.jpg",
release_date: "1405666800"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "70706",
imdb_id: "tt1931602",
genres : ["Drama"],
title: "Very Good Girls",
directors : ["Naomi Foner"],
actors : ["Dakota Fanning", "Elizabeth Olsen", "Boyd Holbrook", "Demi Moore", "Richard Dreyfuss", "Ellen Barkin", "Peter Sarsgaard", "Clark Gregg", "Kiernan Shipka", "Clare Foley"],
trailer: "http://youtube.com/watch?v=Axxy3gghEhc",
url: "http://trakt.tv/movie/very-good-girls-2013",
tagline: "",
overview: "Two New York City girls pact to lost their virginity during their first summer out of high school. When they both fall for the same street artist, the friends find their connection tested for the first time.",
poster: "http://slurm.trakt.us/images/posters_movies/211207.jpg",
release_date: "1358841600"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "222935",
imdb_id: "tt2582846",
genres : ["Drama", "Romance"],
title: "The Fault in Our Stars",
directors : ["Josh Boone"],
actors : ["Shailene Woodley", "Ansel Elgort", "Willem Dafoe", "Nat Wolff", "Laura Dern", "Sam Trammell", "Mike Birbiglia", "Emily Peachey"],
trailer: "http://youtube.com/watch?v=9ItBvH5J6ss",
url: "http://trakt.tv/movie/the-fault-in-our-stars-2014",
tagline: "One Sick Love Story",
overview: "Despite the tumor-shrinking medical miracle that has bought her a few years, Hazel has never been anything but terminal, her final chapter inscribed upon diagnosis. But when a patient named Augustus Waters suddenly appears at Cancer Kid Support Group, Hazels story is about to be completely rewritten.",
poster: "http://slurm.trakt.us/images/posters_movies/223002.2.jpg",
release_date: "1400223600"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "216282",
imdb_id: "tt2106361",
genres : ["Action", "Thriller"],
title: "Into the Storm",
directors : ["Steven Quale"],
actors : ["Richard Armitage", "Jeremy Sumpter", "Nathan Kress", "Matt Walsh", "Kyle Davis", "Scott Lawrence", "Brandon Ruiter"],
trailer: "http://youtube.com/watch?v=EVg8nKNGC5E",
url: "http://trakt.tv/movie/into-the-storm-2014",
tagline: "",
overview: "A group of high school students document the events and aftermath of a devastating tornado",
poster: "http://slurm.trakt.us/images/posters_movies/224047.3.jpg",
release_date: "1407481200"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "299739",
imdb_id: "tt2245172",
genres : [],
title: "Real Heroes",
directors : [],
actors : [],
trailer: "http://youtube.com/watch?v=5Bwl0kAb7AY",
url: "http://trakt.tv/movie/real-heroes-2014",
tagline: "",
overview: "A group of B-string superheroes go on a reality show in hopes of hitting the big time.",
poster: "http://slurm.trakt.us/images/posters_movies/243508.jpg",
release_date: "1415347200"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "232672",
imdb_id: "tt1086772",
genres : ["Comedy"],
title: "Blended",
directors : ["Frank Coraci"],
actors : ["Drew Barrymore", "Adam Sandler", "Wendi McLendon-Covey", "Bella Thorne", "Terry Crews", "Joel McHale", "Lauren Lapkus", "Kevin Nealon", "Dan Patrick", "Alyvia Alyn Lind", "Emma Fuhrmann", "Susan Yeagley", "Anna Colwell", "Abdoulaye NGom", "Kyle Red Silverstein"],
trailer: "http://youtube.com/watch?v=8MuWt2X59fo",
url: "http://trakt.tv/movie/blended-2014",
tagline: "Single Dad, No Clue. Single Mum, Flying Solo.",
overview: "After a bad blind date, a man and woman find themselves stuck together at a resort for families, where their attractions grows as their respective kids benefit from the burgeoning relationship.",
poster: "http://slurm.trakt.us/images/posters_movies/224842.2.jpg",
release_date: "1400828400"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "254191",
imdb_id: "tt3177316",
genres : ["Thriller", "Horror"],
title: "Honeymoon",
directors : ["Leigh Janiak"],
actors : ["Rose Leslie", "Harry Treadaway", "Ben Huber", "Hanna Brown"],
trailer: "http://youtube.com/watch?v=OrSh2CHmEW4",
url: "http://trakt.tv/movie/honeymoon-2014",
tagline: "After the ceremony comes the ritual.",
overview: "Young newlyweds Paul (Harry Treadaway) and Bea (Rose Leslie) travel to remote lake country for their honeymoon, where the promise of private romance awaits them. Shortly after arriving, Paul finds Bea wandering and disoriented in the middle of the night. As she becomes more distant and her behavior increasingly peculiar, Paul begins to suspect something more sinister than sleepwalking took place in the woods.",
poster: "http://slurm.trakt.us/images/posters_movies/229959.jpg",
release_date: "1394179200"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "188161",
imdb_id: "tt2557490",
genres : ["Comedy", "Western"],
title: "A Million Ways to Die in the West",
directors : ["Seth MacFarlane"],
actors : ["Seth MacFarlane", "Charlize Theron", "Liam Neeson", "Amanda Seyfried", "Neil Patrick Harris", "Giovanni Ribisi", "Sarah Silverman", "Wes Studi", "Evan Jones", "Preston Bailey", "Ralph Garman", "Challen Cates", "Dennis Haskins", "Rex Linn"],
trailer: "http://youtube.com/watch?v=KniKvVxaM1o",
url: "http://trakt.tv/movie/a-million-ways-to-die-in-the-west-2014",
tagline: "Bring protection.",
overview: "As a cowardly farmer begins to fall for the mysterious new woman in town, he must put his new-found courage to the test when her husband, a notorious gun-slinger, announces his arrival.",
poster: "http://slurm.trakt.us/images/posters_movies/222875.2.jpg",
release_date: "1401433200"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "98566",
imdb_id: "tt1291150",
genres : ["Action", "Adventure", "Comedy", "Fantasy", "Science Fiction"],
title: "Teenage Mutant Ninja Turtles",
directors : ["Jonathan Liebesman"],
actors : ["Megan Fox", "Will Arnett", "William Fichtner", "Alan Ritchson", "Noel Fisher", "Pete Ploszek", "Johnny Knoxville", "Jeremy Howard", "Abby Elliott", "Danny Woodburn", "Tony Shalhoub", "Tohoru Masamune", "Whoopi Goldberg", "Minae Noji", "Madison Mason", "Derek Mears"],
trailer: "http://youtube.com/watch?v=nCjsWpM9zFU",
url: "http://trakt.tv/movie/teenage-mutant-ninja-turtles-2014",
tagline: "Mysterious. Dangerous. Reptilious. Youve never seen heroes like this.",
overview: "The city needs heroes. Darkness has settled over New York City as Shredder and his evil Foot Clan have an iron grip on everything from the police to the politicians. The future is grim until four unlikely outcast brothers rise from the sewers and discover their destiny as Teenage Mutant Ninja Turtles. The Turtles must work with fearless reporter April and her wise-cracking cameraman Vern Fenwick to save the city and unravel Shredders diabolical plan.",
poster: "http://slurm.trakt.us/images/posters_movies/197630.3.jpg",
release_date: "1407481200"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "82702",
imdb_id: "tt1646971",
genres : ["Action", "Adventure", "Animation", "Comedy", "Fantasy", "Family"],
title: "How to Train Your Dragon 2",
directors : ["Dean DeBlois"],
actors : ["Jay Baruchel", "Gerard Butler", "Kristen Wiig", "Jonah Hill", "Cate Blanchett", "Djimon Hounsou", "Kit Harington", "Christopher Mintz-Plasse", "T.J. Miller", "America Ferrera", "Craig Ferguson"],
trailer: "http://youtube.com/watch?v=xKYZdVmk5Gs",
url: "http://trakt.tv/movie/how-to-train-your-dragon-2-2014",
tagline: "The training is over.",
overview: "The thrilling second chapter of the epic How To Train Your Dragon trilogy brings back the fantastical world of Hiccup and Toothless five years later. While Astrid, Snotlout and the rest of the gang are challenging each other to dragon races (the islands new favorite contact sport), the now inseparable pair journey through the skies, charting unmapped territories and exploring new worlds. When one of their adventures leads to the discovery of a secret ice cave that is home to hundreds of new wild dragons and the mysterious Dragon Rider, the two friends find themselves at the center of a battle to protect the peace.",
poster: "http://slurm.trakt.us/images/posters_movies/188775.2.jpg",
release_date: "1402642800"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "82703",
imdb_id: "tt0864835",
genres : ["Animation", "Adventure", "Family"],
title: "Mr. Peabody & Sherman",
directors : ["Rob Minkoff"],
actors : ["Ty Burrell", "Max Charles", "Ariel Winter", "Allison Janney", "Ellie Kemper", "Stephen Colbert", "Stephen Tobolowsky", "Karan Brar", "Joshua Rush", "Adam Alexi-Malle", "Stanley Tucci", "Laurie Fraser", "Leslie Mann", "Lake Bell"],
trailer: "http://youtube.com/watch?v=GyjoeLAGaWQ",
url: "http://trakt.tv/movie/mr-peabody-and-sherman-2014",
tagline: "Hes Leaving His Mark On History",
overview: "A young boy and his dog, who happens to have a genius-level IQ, spring into action when their time-travel machine is stolen and moments in history begin to be changed.",
poster: "http://slurm.trakt.us/images/posters_movies/211215.2.jpg",
release_date: "1391760000"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "93456",
imdb_id: "tt1690953",
genres : ["Animation", "Family", "Comedy"],
title: "Despicable Me 2",
directors : ["Chris Renaud", "Pierre Coffin"],
actors : ["Steve Carell", "Jason Segel", "Kristen Wiig", "Benjamin Bratt", "Miranda Cosgrove", "Russell Brand", "Ken Jeong", "Steve Coogan", "Elsie Kate Fisher", "Dana Gaier", "Moises Arias", "Nasim Pedrad", "Kristen Schaal"],
trailer: "http://youtube.com/watch?v=HwXbtZXjbVE",
url: "http://trakt.tv/movie/despicable-me-2-2013",
tagline: "Back 2 Work",
overview: "Gru is recruited by the Anti-Villain League to help deal with a powerful new super criminal.",
poster: "http://slurm.trakt.us/images/posters_movies/193058.4.jpg",
release_date: "1372748400"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "278",
imdb_id: "tt0111161",
genres : ["Drama", "Crime"],
title: "The Shawshank Redemption",
directors : ["Frank Darabont"],
actors : ["Tim Robbins", "Morgan Freeman", "Bob Gunton", "William Sadler", "Clancy Brown", "Gil Bellows", "Mark Rolston", "James Whitmore", "Jeffrey DeMunn", "Renee Blaine", "Brian Delate", "Larry Brandenburg", "Neil Giuntoli", "Brian Libby", "David Proval", "Joseph Ragno", "Jude Ciccolella", "Paul McCrane", "Scott Mann", "John Horton", "Gordon Greene", "Alfonso Freeman", "V.J. Foster", "John E. Summers", "Frank Medrano", "Mack Miles", "Alan R. Kessler", "Morgan Lund", "Cornell Wallace", "Gary Lee Davis", "Neil Summers", "Ned Bellamy", "Joe Pecoraro", "Harold E. Cope Jr.", "Don McManus", "Donald Zinn"],
trailer: "http://youtube.com/watch?v=WawU4ouldxU",
url: "http://trakt.tv/movie/the-shawshank-redemption-1994",
tagline: "Fear can hold you prisoner. Hope can set you free.",
overview: "Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
poster: "http://slurm.trakt.us/images/posters_movies/353.2.jpg",
release_date: "779526000"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "244506",
imdb_id: "tt2994190",
genres : ["Drama"],
title: "Camp X-Ray",
directors : ["Peter Sattler"],
actors : ["Kristen Stewart", "Peyman Moaadi", "Lane Garrison", "Joseph Julian Soria", "John Carroll Lynch", "Julia Duffy"],
trailer: "http://youtube.com/watch?v=NQ4JwzxwH-E",
url: "http://trakt.tv/movie/camp-xray-2014",
tagline: "",
overview: "A young woman joins the military to be part of something bigger than herself and her small-town roots. Instead, she ends up as a new guard at Guantanamo Bay, where her mission is far from black and white. Surrounded by hostile jihadists and aggressive squadmates, she strikes up an unusual friendship with one of the detainees.",
poster: "http://slurm.trakt.us/images/posters_movies/227579.jpg",
release_date: "1413529200"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "205596",
imdb_id: "tt2084970",
genres : [],
title: "The Imitation Game",
directors : ["Morten Tyldum"],
actors : ["Benedict Cumberbatch", "Keira Knightley", "Mark Strong", "Rory Kinnear", "Charles Dance", "Allen Leech", "Matthew Goode", "Tuppence Middleton", "Steven Waddington", "Hayley Joanne Bacon", "Tom Goodman-Hill", "Hannah Flynn", "Matthew Beard", "Ancuta Breaban", "James Northcote", "Victoria Wicks", "Bartosz Wandrykow", "Alex Lawther", "Leigh Dent", "Grace Calder", "Lese Asquith-Coe", "William Bowden", "Jack Bannon", "Luke Hope", "Alexander Cooper", "Joseph Oliveira", "Guna Gultniece", "Lauren Beacham", "Nicola-Jayne Wells", "Esther Eden", "Jack Tarlton", "Alex Corbet Burcher", "Stuart Matthews", "Sam Exley", "Lisa Colquhoun", "David G. Robinson", "Charlie Manton", "David Charkham", "Ilan Goodman", "Peter Brown", "Denis Koroshko", "Richard Campbell", "Ben Farrow", "Laurence Kennedy", "John Redmann", "Josh Wichard", "Ingrid Benussi", "Adam Nowell", "Mike Firth", "Daniel Chapple", "Oscar Hatton", "Nicolas Blatt", "Samantha Moran", "James G. Nunn", "Jack Brash", "Benjamin Hardie", "Harry Leonard Parkinson", "Amber-Rose May", "Dominik Charman", "James Gard", "Vincent Idearson", "Alice Tapfield"],
trailer: "http://youtube.com/watch?v=S5CjKEFb-sM",
url: "http://trakt.tv/movie/the-imitation-game-2014",
tagline: "",
overview: "Based on the real life story of legendary cryptanalyst Alan Turing, the film portrays the nail-biting race against time by Turing and his brilliant team of code-breakers at Britains top-secret Government Code and Cypher School at Bletchley Park, during the darkest days of World War II.",
poster: "http://slurm.trakt.us/images/posters_movies/220253.jpg",
release_date: "1416556800"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "242224",
imdb_id: "tt2321549",
genres : ["Horror"],
title: "The Babadook",
directors : ["Jennifer Kent"],
actors : ["Essie Davis", "Noah Wiseman", "Daniel Henshall", "Hayley McElhinney", "Cathy Adamek", "Craig Behenna"],
trailer: "http://youtube.com/watch?v=szaLnKNWC-U",
url: "http://trakt.tv/movie/the-babadook-2014",
tagline: "If its in a word, or its in a look, you cant get rid of the Babadook.",
overview: "A single mom is plagued by the death of husband, and discovers a horrifying presence surrounds her.",
poster: "http://slurm.trakt.us/images/posters_movies/227682.1.jpg",
release_date: "1417161600"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "184098",
imdb_id: "tt2239832",
genres : ["Comedy", "Romance"],
title: "Think Like a Man Too",
directors : ["Tim Story"],
actors : ["Kevin Hart", "Romany Malco", "Terrence Jenkins", "Michael Ealy", "Gary Owen", "Jerry Ferrara", "Regina Hall", "Meagan Good", "Taraji P. Henson", "Gabrielle Union", "Wendi McLendon-Covey", "La La Anthony", "Adam Brody", "David Walton", "Jenifer Lewis"],
trailer: "http://youtube.com/watch?v=N8b6kVSZNLE",
url: "http://trakt.tv/movie/think-like-a-man-too-2014",
tagline: "",
overview: "All the couples are back for a wedding in Las Vegas, but plans for a romantic weekend go awry when their various misadventures get them into some compromising situations that threaten to derail the big event.",
poster: "http://slurm.trakt.us/images/posters_movies/221341.1.jpg",
release_date: "1403247600"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "209189",
imdb_id: "tt1663207",
genres : [],
title: "Life of Crime",
directors : ["Daniel Schechter"],
actors : ["John Hawkes", "Mos Def", "Jennifer Aniston", "Tim Robbins", "Isla Fisher", "Will Forte", "Mark Boone Junior", "Kevin Cannon", "Julie E. Davis", "Seana Kofoed"],
trailer: "http://youtube.com/watch?v=Fpq8v0ItU0c",
url: "http://trakt.tv/movie/life-of-crime-2014",
tagline: "Right target. Wrong woman.",
overview: "Two common criminals get more than they bargained for after kidnapping the wife of a corrupt real-estate developer who shows no interest in paying the $1 million dollar ransom for her safe return.",
poster: "http://slurm.trakt.us/images/posters_movies/228948.jpg",
release_date: "1409295600"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "220471",
imdb_id: "tt2290739",
genres : [],
title: "The Devils Hand",
directors : ["Christian E. Christiansen"],
actors : ["Rufus Sewell", "Alycia Debnam Carey", "Adelaide Kane", "Leah Pipes", "Thomas McDonell", "Jennifer Carpenter", "Jim McKeny", "Katie Garfield", "Ric Reitz", "Ethan Alexander McGee", "Jon Stafford", "Jane McNeill", "Holli Saperstein", "Stacy Rabon", "Robin Dale Robertson"],
trailer: "http://youtube.com/watch?v=uigIV1ALQYQ",
url: "http://trakt.tv/movie/the-devils-hand-2014",
tagline: "Forgive me father for I am sin",
overview: "Five young Amish girls accused of being Satans children must fight for their lives when their devout community elders insist they be cleansed before turning 18.",
poster: "http://slurm.trakt.us/images/posters_movies/222847.jpg",
release_date: "1412924400"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "286532",
imdb_id: "tt0910885",
genres : [],
title: "A Merry Friggin Christmas",
directors : ["Tristram Shapeero"],
actors : ["Robin Williams", "Lauren Graham", "Wendi McLendon-Covey", "Joel McHale", "Jeffrey Tambor", "Matt L. Jones", "Pierce Gagnon", "Candice Bergen", "Oliver Platt", "Clark Duke", "Amir Arison", "Ryan Lee", "Tim Heidecker", "Amara Miller", "Gene Jones", "Mark Proksch", "Bebe Wood", "Parisa Johnston", "Steele Gagnon", "Barak Hardley", "Karan Kendrick", "J.J. Jones", "Michael Shikany"],
trailer: "http://youtube.com/watch?v=TGkBu_qALpg",
url: "http://trakt.tv/movie/a-merry-friggin-christmas-2014",
tagline: "Spend it with the ones you loathe",
overview: "Boyd Mitchler and his family must spend Christmas with his estranged family of misfits. Upon realizing that he left all his sons gifts at home, he hits the road with his dad in an attempt to make the 8-hour round trip before sunrise.",
poster: "http://slurm.trakt.us/images/posters_movies/238742.jpg",
release_date: "1415347200"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "57158",
imdb_id: "tt1170358",
genres : ["Fantasy"],
title: "The Hobbit: The Desolation of Smaug",
directors : ["Peter Jackson"],
actors : ["Martin Freeman", "Ian McKellen", "Richard Armitage", "Ken Stott", "Graham McTavish", "William Kircher", "James Nesbitt", "Stephen Hunter", "Dean OGorman", "Aidan Turner", "Benedict Cumberbatch", "Lee Pace", "Luke Evans", "Evangeline Lilly", "Orlando Bloom", "Billy Connolly", "Hugo Weaving", "Mikael Persbrandt", "Christopher Lee", "Manu Bennett", "Stephen Fry", "Andy Serkis", "John Bell", "Ian Holm", "Sylvester McCoy", "Elijah Wood", "Terry Notary", "Adam Brown", "Peter Hambleton", "Cate Blanchett", "Stephen Colbert", "Jed Brophy", "Sarah Peirse", "Mary Nesbitt", "Peggy Nesbitt"],
trailer: "http://youtube.com/watch?v=BcB0znwAdmg",
url: "http://trakt.tv/movie/the-hobbit-the-desolation-of-smaug-2013",
tagline: "Beyond darkness... beyond desolation... lies the greatest danger of all.",
overview: "The Dwarves, Bilbo and Gandalf have successfully escaped the Misty Mountains, and Bilbo has gained the One Ring. They all continue their journey to get their gold back from the Dragon, Smaug.",
poster: "http://slurm.trakt.us/images/posters_movies/180744.3.jpg",
release_date: "1386921600"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "151368",
imdb_id: "tt2409818",
genres : ["Action", "Crime", "Suspense"],
title: "Open Windows",
directors : ["Nacho Vigalondo"],
actors : ["Elijah Wood", "Sasha Grey", "Neil Maskell", "Nacho Vigalondo", "Brian Elder", "Scott Weinberg"],
trailer: "http://youtube.com/watch?v=_Qz7DDvTA-I",
url: "http://trakt.tv/movie/open-windows-2014",
tagline: "",
overview: "Nick is excited to discover that hes won a dinner date with his favorite actress, Jill Goddard. But when Jill refuses to honor the contest, her manager Chord makes an offer he cant refuse: the ability to view Jill secretly via computer. Nick begins watching the unknowing star on her webcam, not realizing that this decision will put both himself and Jill at risk as they enter a terrifying world of cat-and-mouse where nothing-and no one-are as they seem.",
poster: "http://slurm.trakt.us/images/posters_movies/212359.1.jpg",
release_date: "1394434800"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "249164",
imdb_id: "tt1355630",
genres : ["Drama"],
title: "If I Stay",
directors : ["R.J. Cutler"],
actors : ["Chloe Moretz", "Mireille Enos", "Jamie Blackley", "Liana Liberato", "Aliyah OBrien", "Chelah Horsdal", "Joshua Leonard", "Jakob Davies", "Donnie MacNeil", "Ali Milner", "William C. Vaughan", "Gabrielle Cerys Haslett", "Adam Solomonian"],
trailer: "http://youtube.com/watch?v=EpYXsLENmWw",
url: "http://trakt.tv/movie/if-i-stay-2014",
tagline: "",
overview: "Based on Gayle Formans novel of the same name. If I Stay is the story of the gifted classical musician Mia and her boyfriend, Adam, an up and coming indie-rock star. Torn between two paths in life, her art or her relationship, Mia is forced to make an even starker choice between life and death when she is caught in a fatal car accident with her family one snowy morning in Oregon.",
poster: "http://slurm.trakt.us/images/posters_movies/228452.2.jpg",
release_date: "1408690800"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "242512",
imdb_id: "tt1204977",
genres : ["Horror"],
title: "Ouija",
directors : ["Stiles White"],
actors : ["Olivia Cooke", "Ana Coto", "Daren Kagasoff", "Douglas Smith", "Vivis Colombetti", "Bianca Santos", "Erin Moriarty", "Shelley Hennig"],
trailer: "http://youtube.com/watch?v=xBLmBdn2QF8",
url: "http://trakt.tv/movie/ouija-2014",
tagline: "Keep telling yourself its just a game",
overview: "A group of friends must confront their most terrifying fears when they awaken the dark powers of an ancient spirit board.",
poster: "http://slurm.trakt.us/images/posters_movies/226134.1.jpg",
release_date: "1414134000"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "215379",
imdb_id: "tt2693664",
genres : ["Action", "Drama", "Science Fiction"],
title: "Young Ones",
directors : ["Jake Paltrow"],
actors : ["Nicholas Hoult", "Elle Fanning", "Michael Shannon", "Kodi Smit-McPhee", "Alex McGregor", "Aimee Mullins", "Robert Hobbs"],
trailer: "http://youtube.com/watch?v=nJbtJ6mpkvM",
url: "http://trakt.tv/movie/young-ones-2014",
tagline: "",
overview: "Set in the future when water is hard to find a teenage boy sets out to protect his family and survive.",
poster: "http://slurm.trakt.us/images/posters_movies/227619.1.jpg",
release_date: "1413529200"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "169813",
imdb_id: "tt2370248",
genres : ["Drama"],
title: "Short Term 12",
directors : ["Destin Cretton"],
actors : ["Brie Larson", "John Gallagher Jr.", "Kaitlyn Dever", "Melora Walters", "Stephanie Beatriz", "Rami Malek", "Alex Calloway", "Kevin Hernandez", "Lydia Du Veaux", "Keith Stanfield", "Frantz Turner", "Diana Maria Riva", "Harold Cannon", "Silvia Curiel", "Brandee Allen"],
trailer: "http://youtube.com/watch?v=Cook_OOKWlw",
url: "http://trakt.tv/movie/short-term-12-2013",
tagline: "",
overview: "A 20-something supervising staff member of a residential treatment facility navigates the troubled waters of that world alongside her co-worker and longtime boyfriend.",
poster: "http://slurm.trakt.us/images/posters_movies/220750.1.jpg",
release_date: "1377241200"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "227159",
imdb_id: "tt2170439",
genres : [],
title: "Horrible Bosses 2",
directors : ["Sean Anders"],
actors : ["Jason Sudeikis", "Jason Bateman", "Charlie Day", "Chris Pine", "Christoph Waltz"],
trailer: "http://youtube.com/watch?v=k7bDzOfakDk",
url: "http://trakt.tv/movie/horrible-bosses-2-2014",
tagline: "",
overview: "The original film starred Jason Bateman, Jason Sudeikis and Charlie Day as a group of friends that decide to kill off each others bosses (played by Jennifer Aniston, Colin Farrel and Kevin Spacey).",
poster: "http://slurm.trakt.us/images/posters_movies/223021.jpg",
release_date: "1416988800"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "61791",
imdb_id: "tt1318514",
genres : ["Science Fiction", "Action", "Drama"],
title: "Rise of the Planet of the Apes",
directors : ["Rupert Wyatt"],
actors : ["Andy Serkis", "Karin Konoval", "Freida Pinto", "James Franco", "John Lithgow", "Leah Gibson", "Tyler Labine", "David Hewlett", "David Oyelowo", "Jamie Harris", "Tom Felton", "Chelah Horsdal", "Brian Cox", "Jesse Reid", "Tracy Spiridakos", "Christopher Gordon", "Terry Notary", "Chris Shields", "Devyn Dalton"],
trailer: "http://youtube.com/watch?v=EbCoDf44oCE",
url: "http://trakt.tv/movie/rise-of-the-planet-of-the-apes-2011",
tagline: "Evolution Becomes Revolution.",
overview: "Scientist Will Rodman is determined to find a cure for Alzheimers, the disease which has slowly consumed his father Charles. Will feels certain he is close to a breakthrough and tests his latest serum on apes, noticing dramatic increases in intelligence and brain activity in the primate subjects... Especially Caesar, his pet chimpanzee.",
poster: "http://slurm.trakt.us/images/posters_movies/165530.2.jpg",
release_date: "1312441200"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "172385",
imdb_id: "tt2357291",
genres : ["Animation", "Family", "Comedy", "Music"],
title: "Rio 2",
directors : ["Carlos Saldanha"],
actors : ["Anne Hathaway", "Leslie Mann", "Jamie Foxx", "Andy Garcia", "Bruno Mars", "Jesse Eisenberg", "Jemaine Clement", "Rodrigo Santoro", "Jake T. Austin", "Amandla Stenberg", "Kristen Chenoweth", "John Leguizamo", "Pierce Gagnon", "Rita Moreno", "Kristin Chenoweth", "Rachel Crow", "Bebel Gilberto"],
trailer: "http://youtube.com/watch?v=hUWsKkMKZBc",
url: "http://trakt.tv/movie/rio-2-2014",
tagline: "Hes villainous, shes venomous.",
overview: "Its a jungle out there for Blu, Jewel and their three kids after theyre hurtled from Rio de Janeiro to the wilds of the Amazon. As Blu tries to fit in, he goes beak-to-beak with the vengeful Nigel, and meets the most fearsome adversary of all: his father-in-law.",
poster: "http://slurm.trakt.us/images/posters_movies/214618.1.jpg",
release_date: "1397199600"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "85350",
imdb_id: "tt1065073",
genres : ["Drama"],
title: "Boyhood",
directors : ["Richard Linklater"],
actors : ["Ellar Coltrane", "Patricia Arquette", "Ethan Hawke", "Lorelei Linklater", "Tamara Jolaine", "Jordan Howard", "Zoe Graham", "Evie Thompson", "Sam Dillon", "Nick Krause", "Shane Graham"],
trailer: "http://youtube.com/watch?v=ESVgF4P221E",
url: "http://trakt.tv/movie/boyhood-2014",
tagline: "12 years in the making.",
overview: "The film tells a story of a divorced couple trying to raise their young son. The story follows the boy for twelve years, from first grade at age 6 through 12th grade at age 17-18, and examines his relationship with his parents as he grows.",
poster: "http://slurm.trakt.us/images/posters_movies/190266.2.jpg",
release_date: "1405062000"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "157841",
imdb_id: "tt1981107",
genres : ["Adventure"],
title: "The Young and Prodigious T.S. Spivet",
directors : ["Jean-Pierre Jeunet"],
actors : ["Kyle Catlett", "Helena Bonham Carter", "Judy Davis", "Callum Keith Rennie", "Niamh Wilson", "Jakob Davies", "Rick Mercer", "Robert Maillet", "Julian Richings", "Dominique Pinon", "Dawn Ford", "Lisa Bronwyn Moore"],
trailer: "http://youtube.com/watch?v=wjOYX_a8GXw",
url: "http://trakt.tv/movie/the-young-and-prodigious-ts-spivet-2014",
tagline: "",
overview: "A 12-year-old cartographer secretly leaves his familys ranch in Montana where he lives with his cowboy father and scientist mother and travels across the country on board a freight train to receive an award at the Smithsonian Institute.",
poster: "http://slurm.trakt.us/images/posters_movies/215251.jpg",
release_date: "1414306800"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "109424",
imdb_id: "tt1535109",
genres : ["Drama", "Action", "Thriller"],
title: "Captain Phillips",
directors : ["Paul Greengrass"],
actors : ["Tom Hanks", "Catherine Keener", "Max Martini", "Chris Mulkey", "Yul Vazquez", "Corey Johnson", "David Warshofsky", "John Magaro", "Michael Chernus", "Barkhad Abdi", "Faysal  Ahmed", "Barkhad Abdirahman", "Mahat M. Ali", "Angus MacInnes", "San Shella", "Amr El-Bayoumi", "Azeez Mohammed"],
trailer: "http://youtube.com/watch?v=eruwOiHoTTo",
url: "http://trakt.tv/movie/captain-phillips-2013",
tagline: "Out here survival is everything.",
overview: "The true story of Captain Richard Phillips and the 2009 hijacking by Somali pirates of the US-flagged MV Maersk Alabama, the first American cargo ship to be hijacked in two hundred years.",
poster: "http://slurm.trakt.us/images/posters_movies/210793.3.jpg",
release_date: "1381474800"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "138103",
imdb_id: "tt2333784",
genres : ["Action", "Adventure", "Thriller"],
title: "The Expendables 3",
directors : ["Patrick Hughes"],
actors : ["Sylvester Stallone", "Jason Statham", "Jackie Chan", "Terry Crews", "Randy Couture", "Antonio Banderas", "Nicolas Cage", "Jet Li", "Wesley Snipes", "Dolph Lundgren", "Glen Powell", "Mel Gibson", "Harrison Ford", "Arnold Schwarzenegger", "Kellan Lutz", "Kelsey Grammer", "Robert Davi", "Ronda Rousey", "Victor Ortiz"],
trailer: "http://youtube.com/watch?v=RHmRpryFjwA",
url: "http://trakt.tv/movie/the-expendables-3-2014",
tagline: "New team. New attitude. New mission.",
overview: "Barney (Stallone), Christmas (Statham) and the rest of the team comes face-to-face with Conrad Stonebanks (Gibson), who years ago co-founded The Expendables with Barney. Stonebanks subsequently became a ruthless arms trader and someone who Barney was forced to kill... or so he thought. Stonebanks, who eluded death once before, now is making it his mission to end The Expendables -- but Barney has other plans. Barney decides that he has to fight old blood with new blood, and brings in a new era of Expendables team members, recruiting individuals who are younger, faster and more tech-savvy. The latest mission becomes a clash of classic old-school style versus high-tech expertise in the Expendables most personal battle yet.",
poster: "http://slurm.trakt.us/images/posters_movies/209065.4.jpg",
release_date: "1408086000"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "49017",
imdb_id: "tt0829150",
genres : ["Action", "Drama", "Fantasy", "War"],
title: "Dracula Untold",
directors : ["Gary Shore"],
actors : ["Luke Evans", "Dominic Cooper", "Sarah Gadon", "Art Parkinson", "Samantha Barks", "Charles Dance", "Charlie Cox", "Diarmaid Murtagh", "Paul Kaye", "William Houston", "Noah Huntley", "Ronan Vibert", "Zach McGowan", "Ferdinand Kingsley", "Dilan Gwyn", "J.J. Murphy", "Thor Kristjansson", "Joseph Long"],
trailer: "http://youtube.com/watch?v=m6wXYp-AMgs",
url: "http://trakt.tv/movie/dracula-untold-2014",
tagline: "Every bloodline has beginning",
overview: "Vlad Tepes is a great hero, but when he learns the Sultan is preparing for battle and needs to form an army of 1,000 boys, including Vlads son, he vows to find a way to protect his family. Vlad turns to dark forces in order to get the power to destroy his enemies and agrees to go from hero to monster as hes turned into the mythological vampire Dracula.",
poster: "http://slurm.trakt.us/images/posters_movies/217324.1.jpg",
release_date: "1412319600"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "201086",
imdb_id: "tt2390237",
genres : ["Comedy"],
title: "Cuban Fury",
directors : ["James Griffith"],
actors : ["Chris ODowd", "Ian McShane", "Rashida Jones", "Nick Frost", "Rory Kinnear", "Olivia Colman", "Ben Radcliffe", "Isabella Steinbarth", "Steve Oram", "Alexandra Roach"],
trailer: "http://youtube.com/watch?v=kTS4AsJprm4",
url: "http://trakt.tv/movie/cuban-fury-2014",
tagline: "Alls fair in Love & Salsa",
overview: "Beneath Bruce Garretts under-confident, overweight exterior, the passionate heart of a salsa king lies dormant. Now, one woman is about to reignite his Latin fire.",
poster: "http://slurm.trakt.us/images/posters_movies/220039.1.jpg",
release_date: "1392364800"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "109439",
imdb_id: "tt1951261",
genres : ["Comedy"],
title: "The Hangover Part III",
directors : ["Todd Phillips"],
actors : ["Bradley Cooper", "Ed Helms", "Zach Galifianakis", "Justin Bartha", "Mike Tyson", "Ken Jeong", "John Goodman", "Melissa McCarthy", "Jeffrey Tambor", "Heather Graham", "Mike Epps", "Sasha Barrese", "Jamie Chung", "Sondra Currie", "Gillian Vigman", "Oliver Cooper", "Mike Vallely", "Grant Holmquist", "Oscar Torre", "Billy Choi", "Jonny Coyne"],
trailer: "http://youtube.com/watch?v=FlNGXOs_vSM",
url: "http://trakt.tv/movie/the-hangover-part-iii-2013",
tagline: "It all ends.",
overview: "This time, theres no wedding. No bachelor party. What could go wrong, right? But when the Wolfpack hits the road, all bets are off.",
poster: "http://slurm.trakt.us/images/posters_movies/200037.5.jpg",
release_date: "1369292400"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "49026",
imdb_id: "tt1345836",
genres : ["Action", "Crime", "Thriller", "Drama"],
title: "The Dark Knight Rises",
directors : ["Christopher Nolan"],
actors : ["Christian Bale", "Gary Oldman", "Tom Hardy", "Joseph Gordon-Levitt", "Anne Hathaway", "Morgan Freeman", "Marion Cotillard", "Michael Caine", "Matthew Modine", "Alon Aboutboul", "Ben Mendelsohn", "Juno Temple", "Nestor Carbonell", "Josh Pence", "Vincent van Ommen", "Tom Conti", "Joey King", "Cillian Murphy", "Liam Neeson", "Warren Brown", "Daniel Sunjata", "Aiden Gillen", "Sam Kennard", "Aliash Tepina", "Nick Julian", "Miranda Nolan", "Aidan Gillen"],
trailer: "http://youtube.com/watch?v=z5Humz3ONgk",
url: "http://trakt.tv/movie/the-dark-knight-rises-2012",
tagline: "The Legend Ends",
overview: "Following the death of District Attorney Harvey Dent, Batman assumes responsibility for Dents crimes to protect the late attorneys reputation and is subsequently hunted by the Gotham City Police Department. Eight years later, Batman encounters the mysterious Selina Kyle and the villainous Bane, a new terrorist leader who overwhelms Gothams finest. The Dark Knight resurfaces to protect a city that has branded him an enemy.",
poster: "http://slurm.trakt.us/images/posters_movies/166841.7.jpg",
release_date: "1342767600"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "389",
imdb_id: "tt0050083",
genres : ["Drama"],
title: "12 Angry Men",
directors : ["Sidney Lumet"],
actors : ["Henry Fonda", "Lee J. Cobb", "Ed Begley", "E.G. Marshall", "Jack Warden", "Martin Balsam", "John Fiedler", "Jack Klugman", "Edward Binns", "Joseph Sweeney", "George Voskovec", "Robert Webber", "Rudy Bond", "James Kelly", "Billy Nelson", "John Savoca"],
trailer: "http://youtube.com/watch?v=OvebOqneLIU",
url: "http://trakt.tv/movie/12-angry-men-1957",
tagline: "Life is in their hands. Death is on their minds.",
overview: "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors prejudices and preconceptions about the trial, the accused, and each other.",
poster: "http://slurm.trakt.us/images/posters_movies/484.2.jpg",
release_date: "-401644800"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "299400",
imdb_id: "tt3922810",
genres : ["Family"],
title: "Santa Claws",
directors : [],
actors : [],
trailer: "http://youtube.com/watch?v=4a_aAoGwevU",
url: "http://trakt.tv/movie/santa-claws-2014",
tagline: "",
overview: "Santa is allergic to cats",
poster: "http://slurm.trakt.us/images/poster-dark.jpg",
release_date: "1415088000"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "109451",
imdb_id: "tt1985966",
genres : ["Animation", "Family"],
title: "Cloudy with a Chance of Meatballs 2",
directors : ["Cody Cameron", "Kris Pearn"],
actors : ["Neil Patrick Harris", "Anna Faris", "Terry Crews", "James Caan", "Andy Samberg", "Kristen Schaal", "Bill Hader", "Benjamin Bratt", "Will Forte", "Melissa Sturm", "Khamani Griffin", "Cody Cameron"],
trailer: "http://youtube.com/watch?v=ApsOmSXMHNY",
url: "http://trakt.tv/movie/cloudy-with-a-chance-of-meatballs-2-2013",
tagline: "Something big was leftover.",
overview: "After the disastrous food storm in the first film, Flint and his friends are forced to leave the town. Flint accepts the invitation from his idol Chester V to join The Live Corp Company, which has been tasked to clean the island, and where the best inventors in the world create technologies for the betterment of mankind. When Flint discovers that his machine still operates and now creates mutant food beasts like living pickles, hungry tacodiles, shrimpanzees and apple pie-thons, he and his friends must return to save the world.",
poster: "http://slurm.trakt.us/images/posters_movies/197670.3.jpg",
release_date: "1380265200"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "157336",
imdb_id: "tt0816692",
genres : ["Science Fiction", "Drama"],
title: "Interstellar",
directors : ["Christopher Nolan"],
actors : ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain", "Michael Caine", "Casey Affleck", "Ellen Burstyn", "Timothee Chalamet", "Mackenzie Foy", "John Lithgow", "Bill Irwin", "Topher Grace", "Wes Bentley", "David Oyelowo", "David Gyasi", "Matt Damon", "William Devane"],
trailer: "http://youtube.com/watch?v=ePbKGoIGAXY",
url: "http://trakt.tv/movie/interstellar-2014",
tagline: "Mankind was born on Earth. It was never meant to die here.",
overview: "Interstellar chronicles the adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.",
poster: "http://slurm.trakt.us/images/posters_movies/213294.1.jpg",
release_date: "1415347200"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "137106",
imdb_id: "tt1490017",
genres : ["Animation", "Comedy"],
title: "The Lego Movie",
directors : ["Chris McKay", "Chris Miller", "Phil Lord"],
actors : ["Chris Pratt", "Elizabeth Banks", "Craig Berry", "Will Ferrell", "Will Arnett", "Morgan Freeman", "Liam Neeson", "Alison Brie", "Amanda Farinos", "Charlie Day", "Cobie Smulders", "Channing Tatum", "Jonah Hill", "Nick Offerman", "Dave Franco", "Todd Hansen", "Will Forte", "Anthony Daniels", "Jadon Sand", "Kelly Lafferty", "Christopher Miller", "Graham Miller", "Doug Nicholas", "Chris Paluszek", "Chris Romano", "Leiki Veskimets"],
trailer: "http://youtube.com/watch?v=gLvmVnKT4cc",
url: "http://trakt.tv/movie/the-lego-movie-2014",
tagline: "Assembling in 2014",
overview: "An ordinary Lego mini-figure, mistakenly thought to be the extraordinary MasterBuilder, is recruited to join a quest to stop an evil Lego tyrant from gluing the universe together.",
poster: "http://slurm.trakt.us/images/posters_movies/211626.3.jpg",
release_date: "1391760000"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "242582",
imdb_id: "tt2872718",
genres : ["Crime", "Drama", "Thriller"],
title: "Nightcrawler",
directors : ["Dan Gilroy"],
actors : ["Jake Gyllenhaal", "Bill Paxton", "Rene Russo", "Kevin Rahm", "Riz Ahmed", "Kathleen York", "Ann Cusack"],
trailer: "http://youtube.com/watch?v=1lEdwqwOttg",
url: "http://trakt.tv/movie/nightcrawler-2014",
tagline: "The City Shines Brightest at Night",
overview: "A driven young man (Gyllenhaal) stumbles upon the underground world of L.A. freelance crime journalism.",
poster: "http://slurm.trakt.us/images/posters_movies/233764.jpg",
release_date: "1414738800"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "137113",
imdb_id: "tt1631867",
genres : ["Action", "Science Fiction"],
title: "Edge of Tomorrow",
directors : ["Doug Liman", "Lisa Vick"],
actors : ["Emily Blunt", "Tom Cruise", "Bill Paxton", "Charlotte Riley", "Lee Asquith-Coe", "Jonas Armstrong", "Kick Gurry", "Franz Drameh", "Tony Way", "Dragomir Mrsic", "Deborah Rosan", "Madeleine Mantock", "Marianne Jean-Baptiste", "Noah Taylor", "Jeremy Piven", "Brendan Gleeson"],
trailer: "http://youtube.com/watch?v=ir1A5gwtl7I",
url: "http://trakt.tv/movie/edge-of-tomorrow-2014",
tagline: "Live, Die, Repeat",
overview: "Major Bill Cage is an officer who has never seen a day of combat when he is unceremoniously demoted and dropped into combat. Cage is killed within minutes, managing to take an alpha alien down with him. He awakens back at the beginning of the same day and is forced to fight and die again... and again - as physical contact with the alien has thrown him into a time loop.",
poster: "http://slurm.trakt.us/images/posters_movies/211625.2.jpg",
release_date: "1402038000"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "177572",
imdb_id: "tt2245084",
genres : ["Action", "Animation", "Comedy", "Science Fiction", "Family"],
title: "Big Hero 6",
directors : ["Chris Williams", "Don Hall"],
actors : ["Jamie Chung", "T.J. Miller", "Maya Rudolph"],
trailer: "http://youtube.com/watch?v=QA9tb_5kMF0",
url: "http://trakt.tv/movie/big-hero-6-2014",
tagline: "",
overview: "The special bond that develops between plus-sized inflatable robot Baymax, and prodigy Hiro Hamada, who team up with a group of friends to form a band of high-tech heroes.",
poster: "http://slurm.trakt.us/images/posters_movies/220830.2.jpg",
release_date: "1415347200"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "276908",
imdb_id: "tt2965412",
genres : [],
title: "Comet",
directors : ["Sam Esmail"],
actors : ["Emmy Rossum", "Justin Long"],
trailer: "http://youtube.com/watch?v=f7jY-g4q58I",
url: "http://trakt.tv/movie/comet-2014",
tagline: "",
overview: "Justin Long and Emmy Rossum are star-crossed lovers whose relationship blooms and unravels over the course of six years in this mysterious, dazzlingly original romance. When a chance encounter brings together the cynical Dell (Long) and the quick-witted Kimberly (Rossum), the stage is set for a tempestuous love affair that unfolds like a puzzle. As the film zigzags back and forth in time-from a meteor shower in LA, to an encounter in a Paris hotel room, to a fateful phone call-an unforgettable portrait of a relationship emerges. Sumptuously shot and boasting incredible chemistry between the leads, Comet is a one-of-a-kind cosmic love story.",
poster: "http://slurm.trakt.us/images/posters_movies/240994.jpg",
release_date: "1417766400"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "287084",
imdb_id: "tt2561546",
genres : ["Horror", "Thriller"],
title: "The Town that Dreaded Sundown",
directors : ["Alfonso Gomez-Rejon"],
actors : ["Addison Timlin", "Spencer Treat Clark", "Joshua Leonard", "Gary Cole", "Veronica Cartwright", "Denis OHare"],
trailer: "http://youtube.com/watch?v=ziRIF0kWOJs",
url: "http://trakt.tv/movie/the-town-that-dreaded-sundown-2014",
tagline: "",
overview: "65 years after a masked serial killer terrorized the small town of Texarkana, the so-called moonlight murders begin again. Is it a copycat or something even more sinister? A lonely high school girl, with dark secrets of her own, may be the key to catching him.",
poster: "http://slurm.trakt.us/images/posters_movies/240778.jpg",
release_date: "1413442800"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "218043",
imdb_id: "tt2467046",
genres : ["Action", "Science Fiction"],
title: "Left Behind",
directors : ["Vic Armstrong"],
actors : ["Nicolas Cage", "Chad Michael Murray", "Lea Thompson", "Nicky Whelan", "Martin Klebba", "Cassie Thompson", "Quinton Aaron", "Jordin Sparks", "Gary Grubbs", "William Ragsdale", "Stephanie Honore"],
trailer: "http://youtube.com/watch?v=GrXe8YDbzYs",
url: "http://trakt.tv/movie/left-behind-2014",
tagline: "",
overview: "A small group of survivors are left behind after millions of people suddenly vanish during the rapture and the world is plunged into chaos and destruction.",
poster: "http://slurm.trakt.us/images/posters_movies/222140.1.jpg",
release_date: "1412319600"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "82507",
imdb_id: "tt1922777",
genres : ["Horror", "Mystery", "Thriller"],
title: "Sinister",
directors : ["Scott Derrickson"],
actors : ["Ethan Hawke", "Vincent DOnofrio", "James Ransone", "Fred Dalton Thompson", "Clare Foley", "Juliet Rylance", "Cameron Ocasio", "Michael Hall DAddario", "Victoria Leigh", "Blake Mizrahi"],
trailer: "http://youtube.com/watch?v=pgYxydrVlDk",
url: "http://trakt.tv/movie/sinister-2012",
tagline: "Once you see him, nothing can save you.",
overview: "Found footage helps a true-crime novelist realize how and why a family was murdered in his new home, though his discoveries put his entire family in the path of a supernatural entity.",
poster: "http://slurm.trakt.us/images/posters_movies/191477.2.jpg",
release_date: "1350025200"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "239563",
imdb_id: "tt2170593",
genres : ["Comedy"],
title: "St. Vincent",
directors : ["Theodore Melfi"],
actors : ["Bill Murray", "Melissa McCarthy", "Naomi Watts", "Chris ODowd", "Terrence Howard", "Selenis Leyva", "Nathan Corddry", "Katharina Damm", "Scott Adsit", "Jaeden Lieberher", "Kimberly Quinn", "Lenny Venito", "Alyssa Ruland", "Alexandra Fong", "Greta Lee", "James Andrew OConnor", "Casey Roberts", "Dario Barosso"],
trailer: "http://youtube.com/watch?v=BCJDuqLuPZA",
url: "http://trakt.tv/movie/st-vincent-2014",
tagline: "",
overview: "A young boy whose parents just divorced finds an unlikely friend and mentor in the misanthropic, bawdy, hedonistic, war veteran who lives next door.",
poster: "http://slurm.trakt.us/images/posters_movies/226741.1.jpg",
release_date: "1414738800"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "295379",
imdb_id: "tt4047132",
genres : ["Comedy", "Romance"],
title: "Oru Oorla Rendu Raja",
directors : ["R Kannan"],
actors : ["Vimal", "Priya Anand", "Soori", "Nassar", "Anupama Kumar", "Thambi Ramaiah", "Vishakha Singh", "Iniya"],
trailer: "http://youtube.com/watch?v=O7dvxtSYjSE",
url: "http://trakt.tv/movie/oru-oorla-rendu-raja-2014",
tagline: "",
overview: "The film revolves around Vimal, an educated youth who from hails from a rural background. Things go topsy-turvy when he falls in love with Annapoorni and lands in trouble due to his free-spirited nature.",
poster: "http://slurm.trakt.us/images/posters_movies/243354.jpg",
release_date: "1415347200"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "282069",
imdb_id: "tt3345472",
genres : ["Horror", "Science Fiction"],
title: "Parasyte: Part 1",
directors : ["Takashi Yamazaki"],
actors : [],
trailer: "http://youtube.com/watch?v=amMR_8YDJgc",
url: "http://trakt.tv/movie/parasyte-part-1-2014",
tagline: "",
overview: "Alien pods come to Earth and, naturally, start taking over Human Hosts. One such pod only manages to take over one humans, Shin Izumi, right arm. Together they grow and co-exist, all the while the other aliens are making meals of other humans; Shin feels he must put a stop to it all, but his alien, Migi, doesnt see why.",
poster: "http://slurm.trakt.us/images/posters_movies/237139.jpg",
release_date: "1417248000"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "273881",
imdb_id: "tt3744464",
genres : ["Action", "Adventure", "Science Fiction"],
title: "Space Sheriff Shaider: THE NEXT GENERATION",
directors : [],
actors : [],
trailer: "http://youtube.com/watch?v=Ykzl6rU0v-I",
url: "http://trakt.tv/movie/space-sheriff-shaider-the-next-generation-2014",
tagline: "",
overview: "This new Space Sheriff project is a V-Cinema project that takes place after the events of Space Sheriff Gavan the Movie. Space Sheriff Shaider: THE NEXT GENERATION will be released on November 7th. Its expected that Hiroaki Iwanaga will reprise his role as Shu Karasuma/Shaider for the film.",
poster: "http://slurm.trakt.us/images/posters_movies/241769.jpg",
release_date: "1415347200"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "51162",
imdb_id: "tt1449283",
genres : ["Adventure", "Animation", "Family"],
title: "Winnie the Pooh",
directors : ["Don Hall", "Stephen Anderson"],
actors : ["Travis Oates", "Jim Cummings", "Bud Luckey", "Craig Ferguson", "Tom Kenny", "Kirsten Anderson-Lopez", "Wyatt Hall", "Jack Bouleter", "Huell Howser", "John Cleese"],
trailer: "http://youtube.com/watch?v=hRT86ZggCEk",
url: "http://trakt.tv/movie/winnie-the-pooh-2011",
tagline: "Oh Pooh.",
overview: "During an ordinary day in Hundred Acre Wood, Winnie the Pooh sets out to find some honey. Misinterpreting a note from Christopher Robin, Pooh convinces Tigger, Rabbit, Piglet, Owl, Kanga, Roo, and Eeyore that their young friend has been captured by a creature named Backson and they set out to save him.",
poster: "http://slurm.trakt.us/images/posters_movies/2164.jpg",
release_date: "1310626800"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "243683",
imdb_id: "tt2626350",
genres : [],
title: "Step Up All In",
directors : ["Trish Sie"],
actors : ["Ryan Guzman", "Briana Evigan", "Stephen Boss", "Misha Gabriel", "Izabella Miko", "Alyson Stoner", "Adam G. Sevani", "Chadd Smith", "Christopher Scott", "Chaton Anderson", "Mari Koda"],
trailer: "http://youtube.com/watch?v=0Gr3cqL4ziE",
url: "http://trakt.tv/movie/step-up-all-in-2014",
tagline: "",
overview: "All-stars from the previous Step Up installments come together in glittering Las Vegas, battling for a victory that could define their dreams and their careers.",
poster: "http://slurm.trakt.us/images/posters_movies/228244.jpg",
release_date: "1406271600"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "124905",
imdb_id: "tt0831387",
genres : ["Action"],
title: "Godzilla",
directors : ["Gareth Edwards", "Jessica Clothier"],
actors : ["Aaron Johnson", "CJ Adams", "Ken Watanabe", "Bryan Cranston", "Elizabeth Olsen", "Carson Bolde", "Sally Hawkins", "Juliette Binoche", "David Strathairn", "Richard T. Jones", "Victor Rasuk", "Patrick Sabongui", "Jared Keeso", "Luc Roderique", "James Pizzinato", "Al Sapienza", "Brian Markinson", "Yuki Mortia", "Chris Shields"],
trailer: "http://youtube.com/watch?v=7UWYM_zMOIA",
url: "http://trakt.tv/movie/godzilla-2014",
tagline: "A kings arrival is never silent.",
overview: "Fifteen years after an incident at a Japanese nuclear power plant, physicist Joe Brody joins forces with his soldier son Ford to discover for themselves what really happened.  What they uncover is prelude to global-threatening devastation.  An epic rebirth to Tohos iconic Godzilla, this spectacular adventure pits the worlds most famous monster against malevolent creatures who, bolstered by humanitys scientific arrogance, threaten our very existence.",
poster: "http://slurm.trakt.us/images/posters_movies/203830.2.jpg",
release_date: "1400223600"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "244566",
imdb_id: "tt2581244",
genres : ["Comedy", "Horror"],
title: "Life After Beth",
directors : ["Jeff Baena"],
actors : ["Aubrey Plaza", "Dane DeHaan", "John C. Reilly", "Molly Shannon", "Cheryl Hines", "Paul Reiser", "Anna Kendrick", "Alia Shawkat", "Matthew Gray Gubler", "Eva La Dare"],
trailer: "http://youtube.com/watch?v=BAGUWBGPffo",
url: "http://trakt.tv/movie/life-after-beth-2014",
tagline: "Be Careful What You Wish For...",
overview: "Zach is devastated by the unexpected death of his girlfriend, Beth. When she mysteriously returns, he gets a second chance at love. Soon his whole world turns upside down...",
poster: "http://slurm.trakt.us/images/posters_movies/226556.jpg",
release_date: "1408086000"}).save(function(err, n) {});