var UpcomingMovies = require('../models/upcoming_movies');

new UpcomingMovies({tmdb_id: "151595",
imdb_id: "tt2118609",
genres : [],
title: "Death Metal Angola",
directors : ["Jeremy Xido"],
actors : ["Sonia Ferreira", "Wilker Flores"],
trailer: "http://youtube.com/watch?v=yuG9xc2Qhzs",
url: "http://trakt.tv/movie/death-metal-angola-2014",
tagline: "",
release_date: "1415347200"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "290864",
imdb_id: "tt2952602",
genres : ["Action", "Crime", "Thriller"],
title: "Kung Fu Jungle",
directors : ["Teddy Chan"],
actors : ["Donnie Yen", "Fan Siu-wong", "Bai Bing", "Baoqiang Wang", "Charlie Yeung"],
trailer: "http://youtube.com/watch?v=http://youtu.be/w0HP6S9vHr8",
url: "http://trakt.tv/movie/kung-fu-jungle-2014",
tagline: "Kung Fu is a Skill for Killing",
release_date: "1414738800"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "297019",
imdb_id: "tt3848888",
genres : ["Comedy"],
title: "The Shaukeens",
directors : ["Abhishek Sharma"],
actors : ["Akshay Kumar", "Lisa Haydon", "Anupam Kher", "Annu Kapoor"],
trailer: "http://youtube.com/watch?v=eg4tfauEn7c",
url: "http://trakt.tv/movie/the-shaukeens-2014",
tagline: "",
release_date: "1415347200"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "290930",
imdb_id: "tt3089922",
genres : [],
title: "Image",
directors : [],
actors : [],
trailer: "http://youtube.com/watch?v=6JvQiMZ_si8",
url: "http://trakt.tv/movie/image-2014",
tagline: "",
release_date: "1415174400"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "204922",
imdb_id: "tt1726592",
genres : [],
title: "Before I Go to Sleep",
directors : ["Rowan Joffe"],
actors : ["Nicole Kidman", "Colin Firth", "Mark Strong", "Anne-Marie Duff", "Jing Lusi", "Dean-Charles Chapman"],
trailer: "http://youtube.com/watch?v=ag1tQ31nW40",
url: "http://trakt.tv/movie/before-i-go-to-sleep-2014",
tagline: "",
release_date: "1414738800"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "245891",
imdb_id: "tt2911666",
genres : ["Action", "Thriller"],
title: "John Wick",
directors : ["Chad Stahelski", "David Leitch"],
actors : ["Keanu Reeves", "Adrianne Palicki", "Bridget Regan", "Willem Dafoe", "Bridget Moynahan", "Jason Isaacs", "Alfie Allen", "Omer Barnea", "Lance Reddick", "Toby Leonard Moore"],
trailer: "http://youtube.com/watch?v=RllJtOw0USI",
url: "http://trakt.tv/movie/john-wick-2014",
tagline: "Don't set him off.",
release_date: "1414134000"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "157841",
imdb_id: "tt1981107",
genres : ["Adventure"],
title: "The Young and Prodigious T.S. Spivet",
directors : ["Jean-Pierre Jeunet"],
actors : ["Kyle Catlett", "Helena Bonham Carter", "Judy Davis", "Callum Keith Rennie", "Niamh Wilson", "Jakob Davies", "Rick Mercer", "Robert Maillet", "Julian Richings", "Dominique Pinon", "Dawn Ford", "Lisa Bronwyn Moore"],
trailer: "http://youtube.com/watch?v=wjOYX_a8GXw",
url: "http://trakt.tv/movie/the-young-and-prodigious-ts-spivet-2014",
tagline: "",
release_date: "1414306800"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "297125",
imdb_id: "tt4047140",
genres : ["Action", "Romance"],
title: "Poojai",
directors : ["Hari"],
actors : ["Vishal Krishna", "Shruti Haasan", "Soori", "Mukesh Tiwari", "Jayaprakash", "Thalaivasal Vijay", "Prathap K Pothan", "Pandi", "Manobala", "R. Sundarrajan", "Imman Annachi", "Radhika Sarathkumar", "Abinaya", "Kausalya", "Sithara"],
trailer: "http://youtube.com/watch?v=imq3oDkPhw0",
url: "http://trakt.tv/movie/poojai-2014",
tagline: "",
release_date: "1413961200"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "298026",
imdb_id: "tt3081268",
genres : ["Crime", "Horror", "Science Fiction"],
title: "Reaper",
directors : ["Wen-Han Shih"],
actors : ["Danny Trejo", "Vinnie Jones", "Jake Busey", "Shayla Beesley", "James Jurdi", "Christopher Judge", "Justin Henry", "William Shockley", "Gabriel Jarret", "Mike Michaels", "Ian Fisher", "Dustin Aremburg", "Shay Moulder", "Joshua Neyman", "Michael Rudie", "J.J. Sicotte"],
trailer: "http://youtube.com/watch?v=jamwIaTdMhE",
url: "http://trakt.tv/movie/reaper-2014",
tagline: "Death to the wicked",
release_date: "1414652400"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "298714",
imdb_id: "",
genres : ["Drama", "Thriller"],
title: "X",
directors : [],
actors : ["Aditi Chengappa", "Bidita Bag", "Gabriella Schmidt", "Huma Qureshi", "Neha Mahajan", "Parno Mitra", "Piaa Bajpai", "Pooja Ruparel", "Radhika Apte", "Richa Shukla", "Rituparna Sengupta", "Swara Bhaskar", "Rajat Kapoor", "Anshuman Jha"],
trailer: "http://youtube.com/watch?v=GxpEKLcbltY",
url: "http://trakt.tv/movie/x-2014",
tagline: "Past is Present",
release_date: "1416556800"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "280884",
imdb_id: "",
genres : [],
title: "Jai Hind 2",
directors : ["Arjun Sarja"],
actors : ["Arjun Sarja", "Surveen Chawla", "Rahul Dev", "Charlotte Claire", "Brahmanandam", "Mayilsamy", "Atul Mathur", "Manobala", "Vinaya Prasad"],
trailer: "http://youtube.com/watch?v=DLvSOmUepVc",
url: "http://trakt.tv/movie/jai-hind-2-2014",
tagline: "",
release_date: "1420012800"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "172390",
imdb_id: "tt1977087",
genres : [],
title: "Tom Sawyer & Huckleberry Finn",
directors : ["Jo Kastner"],
actors : ["Val Kilmer", "Katherine McNamara", "Jake T. Austin", "Joel Courtney", "Noah Munck", "Christine Kaufmann", "Velizar Binev", "Dan van Husen", "Miles Mussenden", "Sewell Whitney"],
trailer: "http://youtube.com/watch?v=OnJD6mWlbRw",
url: "http://trakt.tv/movie/tom-sawyer-and-huckleberry-finn-2014",
tagline: "Everything is about to change.",
release_date: "1414047600"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "299400",
imdb_id: "tt3922810",
genres : ["Family"],
title: "Santa Claws",
directors : [],
actors : [],
trailer: "http://youtube.com/watch?v=4a_aAoGwevU",
url: "http://trakt.tv/movie/santa-claws-2014",
tagline: "",
release_date: "1415088000"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "295379",
imdb_id: "tt4047132",
genres : ["Comedy", "Romance"],
title: "Oru Oorla Rendu Raja",
directors : ["R Kannan"],
actors : ["Vimal", "Priya Anand", "Soori", "Nassar", "Anupama Kumar", "Thambi Ramaiah", "Vishakha Singh", "Iniya"],
trailer: "http://youtube.com/watch?v=O7dvxtSYjSE",
url: "http://trakt.tv/movie/oru-oorla-rendu-raja-2014",
tagline: "",
release_date: "1415347200"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "177572",
imdb_id: "tt2245084",
genres : ["Action", "Animation", "Comedy", "Science Fiction", "Family"],
title: "Big Hero 6",
directors : ["Chris Williams", "Don Hall"],
actors : ["Jamie Chung", "T.J. Miller", "Maya Rudolph"],
trailer: "http://youtube.com/watch?v=QA9tb_5kMF0",
url: "http://trakt.tv/movie/big-hero-6-2014",
tagline: "",
release_date: "1415347200"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "244264",
imdb_id: "tt2034031",
genres : [],
title: "Laggies",
directors : ["Lynn Shelton"],
actors : ["Keira Knightley", "Sam Rockwell", "Chloe Moretz", "Ellie Kemper", "Jeff Garlin", "Mark Webber", "Tiya Sircar", "Kaitlyn Dever"],
trailer: "http://youtube.com/watch?v=4o8peGbqxeI",
url: "http://trakt.tv/movie/laggies-2014",
tagline: "",
release_date: "1414134000"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "131631",
imdb_id: "tt1951265",
genres : ["Adventure", "Science Fiction", "Thriller"],
title: "The Hunger Games: Mockingjay - Part 1",
directors : ["Francis Lawrence"],
actors : ["Jennifer Lawrence", "Josh Hutcherson", "Liam Hemsworth", "Woody Harrelson", "Robert Knepper", "Sam Claflin", "Julianne Moore", "Lily Rabe", "Evan Ross", "Philip Seymour Hoffman", "Elden Henson", "Stef Dawson", "Mahershala Ali", "Wes Chatham"],
trailer: "http://youtube.com/watch?v=7dCB2U9lX48",
url: "http://trakt.tv/movie/the-hunger-games-mockingjay-part-1-2014",
tagline: "",
release_date: "1416556800"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "242224",
imdb_id: "tt2321549",
genres : ["Horror"],
title: "The Babadook",
directors : ["Jennifer Kent"],
actors : ["Essie Davis", "Noah Wiseman", "Daniel Henshall", "Hayley McElhinney", "Cathy Adamek", "Craig Behenna"],
trailer: "http://youtube.com/watch?v=szaLnKNWC-U",
url: "http://trakt.tv/movie/the-babadook-2014",
tagline: "If it's in a word, or it's in a look, you can't get rid of the Babadook.",
release_date: "1417161600"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "270946",
imdb_id: "tt1911658",
genres : [],
title: "Penguins of Madagascar",
directors : ["Simon J. Smith"],
actors : ["Ben Stiller", "Benedict Cumberbatch", "Jada Pinkett Smith", "David Schwimmer", "John Malkovich", "Chris Rock", "Peter Stormare", "John DiMaggio", "Ken Jeong", "Annet Mahendru", "Nicole Sullivan", "Cedric the Entertainer", "Andy Richter", "Tom McGrath", "Chris Miller", "Christopher Knights"],
trailer: "http://youtube.com/watch?v=KHGHEpUeUwo",
url: "http://trakt.tv/movie/penguins-of-madagascar-2014",
tagline: "",
release_date: "1416988800"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "266856",
imdb_id: "tt2980516",
genres : ["Drama"],
title: "The Theory of Everything",
directors : ["James Marsh"],
actors : ["Felicity Jones", "Emily Watson", "Harry Lloyd", "David Thewlis", "Charlotte Hope", "Adam Godley", "Lesley Manville", "Maxine Peake", "Eddie Redmayne"],
trailer: "http://youtube.com/watch?v=1YjF5gV_Tc4",
url: "http://trakt.tv/movie/the-theory-of-everything-2014",
tagline: "",
release_date: "1415347200"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "289416",
imdb_id: "tt3068192",
genres : ["Horror", "Thriller"],
title: "Grace: The Possession",
directors : ["Jeff Chan"],
actors : ["Alexia Fast", "Joel Moore", "Lin Shaye", "Brett Dier", "John Emmett Tracy", "Daniel Arnold"],
trailer: "http://youtube.com/watch?v=ijkk9itwpsQ",
url: "http://trakt.tv/movie/grace-the-possession-2014",
tagline: "Innocence ends in blood",
release_date: "1414479600"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "295588",
imdb_id: "tt2304459",
genres : ["Drama"],
title: "23 Blast",
directors : ["Dylan Baker"],
actors : ["Mark Hapka", "Bram Hoover", "Stephen Lang", "Max Adler", "Alexa Vega", "Dylan Baker", "Kim Zimmer", "Becky Ann Baker", "Timothy Busfield"],
trailer: "http://youtube.com/watch?v=HodFzcJHIYI",
url: "http://trakt.tv/movie/23-blast-2014",
tagline: "Vision Comes from Within",
release_date: "1414134000"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "301748",
imdb_id: "tt2796678",
genres : ["Comedy"],
title: "Opposite Sex",
directors : ["Jennifer Finnigan", "Jonathan Silverman"],
actors : ["Mena Suvari", "Eric Roberts", "Kristin Chenoweth", "Dana Ashbrook", "Kenan Thompson", "Jennifer Finnigan"],
trailer: "http://youtube.com/watch?v=fR4COuXHFdg",
url: "http://trakt.tv/movie/opposite-sex-2014",
tagline: "A battle of the sexes, winner takes all.",
release_date: "1415433600"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "201132",
imdb_id: "tt2773308",
genres : ["Adventure", "Documentary"],
title: "Antarctica: A Year On Ice",
directors : ["Anthony Powell"],
actors : [],
trailer: "http://youtube.com/watch?v=a9EVkLa41V8",
url: "http://trakt.tv/movie/antarctica-a-year-on-ice-2014",
tagline: "Step Outside The Box",
release_date: "1417161600"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "299739",
imdb_id: "tt2245172",
genres : [],
title: "Real Heroes",
directors : [],
actors : [],
trailer: "http://youtube.com/watch?v=5Bwl0kAb7AY",
url: "http://trakt.tv/movie/real-heroes-2014",
tagline: "",
release_date: "1415347200"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "244580",
imdb_id: "tt1864405",
genres : [],
title: "Low Down",
directors : ["Jeff Preiss"],
actors : ["John Hawkes", "Elle Fanning", "Glenn Close", "Peter Dinklage", "Lena Headey", "Flea"],
trailer: "http://youtube.com/watch?v=_0GGjRFeLss",
url: "http://trakt.tv/movie/low-down-2014",
tagline: "",
release_date: "1414134000"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "205596",
imdb_id: "tt2084970",
genres : [],
title: "The Imitation Game",
directors : ["Morten Tyldum"],
actors : ["Benedict Cumberbatch", "Keira Knightley", "Mark Strong", "Rory Kinnear", "Charles Dance", "Allen Leech", "Matthew Goode", "Tuppence Middleton", "Steven Waddington", "Hayley Joanne Bacon", "Tom Goodman-Hill", "Hannah Flynn", "Matthew Beard", "Ancuta Breaban", "James Northcote", "Victoria Wicks", "Bartosz Wandrykow", "Alex Lawther", "Leigh Dent", "Grace Calder", "Lese Asquith-Coe", "William Bowden", "Jack Bannon", "Luke Hope", "Alexander Cooper", "Joseph Oliveira", "Guna Gultniece", "Lauren Beacham", "Nicola-Jayne Wells", "Esther Eden", "Jack Tarlton", "Alex Corbet Burcher", "Stuart Matthews", "Sam Exley", "Lisa Colquhoun", "David G. Robinson", "Charlie Manton", "David Charkham", "Ilan Goodman", "Peter Brown", "Denis Koroshko", "Richard Campbell", "Ben Farrow", "Laurence Kennedy", "John Redmann", "Josh Wichard", "Ingrid Benussi", "Adam Nowell", "Mike Firth", "Daniel Chapple", "Oscar Hatton", "Nicolas Blatt", "Samantha Moran", "James G. Nunn", "Jack Brash", "Benjamin Hardie", "Harry Leonard Parkinson", "Amber-Rose May", "Dominik Charman", "James Gard", "Vincent Idearson", "Alice Tapfield"],
trailer: "http://youtube.com/watch?v=S5CjKEFb-sM",
url: "http://trakt.tv/movie/the-imitation-game-2014",
tagline: "",
release_date: "1416556800"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "242512",
imdb_id: "tt1204977",
genres : ["Horror"],
title: "Ouija",
directors : ["Stiles White"],
actors : ["Olivia Cooke", "Ana Coto", "Daren Kagasoff", "Douglas Smith", "Vivis Colombetti", "Bianca Santos", "Erin Moriarty", "Shelley Hennig"],
trailer: "http://youtube.com/watch?v=xBLmBdn2QF8",
url: "http://trakt.tv/movie/ouija-2014",
tagline: "Keep telling yourself it's just a game",
release_date: "1414134000"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "250745",
imdb_id: "tt2171902",
genres : [],
title: "Happy Valley",
directors : ["Amir Bar-Lev"],
actors : [],
trailer: "http://youtube.com/watch?v=fQH8_-Pd7r4",
url: "http://trakt.tv/movie/happy-valley-2014",
tagline: "",
release_date: "1415952000"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "242582",
imdb_id: "tt2872718",
genres : ["Crime", "Drama", "Thriller"],
title: "Nightcrawler",
directors : ["Dan Gilroy"],
actors : ["Jake Gyllenhaal", "Bill Paxton", "Rene Russo", "Kevin Rahm", "Riz Ahmed", "Kathleen York", "Ann Cusack"],
trailer: "http://youtube.com/watch?v=1lEdwqwOttg",
url: "http://trakt.tv/movie/nightcrawler-2014",
tagline: "The City Shines Brightest at Night",
release_date: "1414738800"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "286873",
imdb_id: "tt2290553",
genres : ["Action", "Adventure"],
title: "Northmen: A Viking Saga",
directors : [],
actors : ["Ryan Kwanten", "Ed Skrein", "Tom Hopper"],
trailer: "http://youtube.com/watch?v=AW7_cACcXD8",
url: "http://trakt.tv/movie/northmen-a-viking-saga-2014",
tagline: "There's No Time To Bleed",
release_date: "1414047600"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "276908",
imdb_id: "tt2965412",
genres : [],
title: "Comet",
directors : ["Sam Esmail"],
actors : ["Emmy Rossum", "Justin Long"],
trailer: "http://youtube.com/watch?v=f7jY-g4q58I",
url: "http://trakt.tv/movie/comet-2014",
tagline: "",
release_date: "1417766400"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "227159",
imdb_id: "tt2170439",
genres : [],
title: "Horrible Bosses 2",
directors : ["Sean Anders"],
actors : ["Jason Sudeikis", "Jason Bateman", "Charlie Day", "Chris Pine", "Christoph Waltz"],
trailer: "http://youtube.com/watch?v=k7bDzOfakDk",
url: "http://trakt.tv/movie/horrible-bosses-2-2014",
tagline: "",
release_date: "1416988800"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "298077",
imdb_id: "tt4127138",
genres : ["Science Fiction"],
title: "Ambition",
directors : ["Tomek Baginski"],
actors : ["Aidan Gillen", "Aisling Franciosi"],
trailer: "http://youtube.com/watch?v=R4XK_NAToRI",
url: "http://trakt.tv/movie/ambition-2014",
tagline: "",
release_date: "1414134000"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "289981",
imdb_id: "tt3241870",
genres : [],
title: "Coming In",
directors : ["Marco Kreuzpaintner"],
actors : ["Kostja Ullmann", "Aylin Tezel", "Katja Riemann", "Ken Duken"],
trailer: "http://youtube.com/watch?v=rWR1Kd2Lpss",
url: "http://trakt.tv/movie/coming-in-2014",
tagline: "",
release_date: "1414047600"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "263475",
imdb_id: "tt3801314",
genres : ["Action", "Romance"],
title: "Knife",
directors : ["A.R. Murugadoss"],
actors : ["Vijay", "Samantha Ruth Prabhu", "Tota Roy Chowdhury", "Satish", "Prabhu", "Panchu Subbu", "Sayaji Shinde", "Neil Nitin Mukesh"],
trailer: "http://youtube.com/watch?v=y7lFjlQHTv8",
url: "http://trakt.tv/movie/knife-2014",
tagline: "",
release_date: "1413961200"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "300441",
imdb_id: "tt3801438",
genres : ["Comedy", "Family"],
title: "Grumpy Cat's Worst Christmas Ever",
directors : [],
actors : ["Grumpy Cat", "Megan Charpentier", "Aubrey Plaza"],
trailer: "http://youtube.com/watch?v=PrSPuBYm-Cw",
url: "http://trakt.tv/movie/grumpy-cats-worst-christmas-ever-2014",
tagline: "",
release_date: "1417248000"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "298400",
imdb_id: "",
genres : ["Drama", "Horror"],
title: "T'yanak",
directors : ["Lore Reyes", "Peque Gallaga"],
actors : ["Judy Ann Santos", "Solenn Heussaff", "Tom Rodriguez", "Sid Lucero"],
trailer: "http://youtube.com/watch?v=SnwYCoJbTrI",
url: "http://trakt.tv/movie/tyanak-2014",
tagline: "",
release_date: "1413961200"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "87492",
imdb_id: "tt1100089",
genres : ["Drama"],
title: "Foxcatcher",
directors : ["Bennett Miller"],
actors : ["Channing Tatum", "Steve Carell", "Mark Ruffalo", "Anthony Michael Hall", "Sienna Miller", "Vanessa Redgrave"],
trailer: "http://youtube.com/watch?v=8fS6IWN81gI",
url: "http://trakt.tv/movie/foxcatcher-2014",
tagline: "",
release_date: "1415952000"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "282069",
imdb_id: "tt3345472",
genres : ["Horror", "Science Fiction"],
title: "Parasyte: Part 1",
directors : ["Takashi Yamazaki"],
actors : [],
trailer: "http://youtube.com/watch?v=amMR_8YDJgc",
url: "http://trakt.tv/movie/parasyte-part-1-2014",
tagline: "",
release_date: "1417248000"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "273881",
imdb_id: "tt3744464",
genres : ["Action", "Adventure", "Science Fiction"],
title: "Space Sheriff Shaider: THE NEXT GENERATION",
directors : [],
actors : [],
trailer: "http://youtube.com/watch?v=Ykzl6rU0v-I",
url: "http://trakt.tv/movie/space-sheriff-shaider-the-next-generation-2014",
tagline: "",
release_date: "1415347200"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "300506",
imdb_id: "tt4047126",
genres : ["Drama", "Romance"],
title: "Nerungi Vaa Muthamidathe",
directors : ["Lakshmi Ramakrishnan"],
actors : ["Shabeer", "Piaa Bajpai", "Sruthi Hariharan", "Viji Chandrasekhar", "Thambi Ramaiah", "Y G Mahendran", "Lakshmi Ramakrishnan", "Thalaivasal Vijay"],
trailer: "http://youtube.com/watch?v=sHoGpdTPXKg",
url: "http://trakt.tv/movie/nerungi-vaa-muthamidathe-2014",
tagline: "",
release_date: "1414738800"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "251516",
imdb_id: "tt3472226",
genres : [],
title: "Kung Fury",
directors : [],
actors : [],
trailer: "http://youtube.com/watch?v=72RqpItxd8M",
url: "http://trakt.tv/movie/kung-fury-2014",
tagline: "",
release_date: "1414825200"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "212606",
imdb_id: "tt2353767",
genres : ["Drama"],
title: "1,000 Times Good Night",
directors : ["Erik Poppe"],
actors : ["Juliette Binoche", "Nikolaj Coster-Waldau", "Maria Doyle Kennedy", "Larry Mullen Jr.", "Eve Macklin"],
trailer: "http://youtube.com/watch?v=hl4jDts4sB0",
url: "http://trakt.tv/movie/1000-times-good-night-2014",
tagline: "",
release_date: "1414134000"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "157336",
imdb_id: "tt0816692",
genres : ["Science Fiction", "Drama"],
title: "Interstellar",
directors : ["Christopher Nolan"],
actors : ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain", "Michael Caine", "Casey Affleck", "Ellen Burstyn", "Timothee Chalamet", "Mackenzie Foy", "John Lithgow", "Bill Irwin", "Topher Grace", "Wes Bentley", "David Oyelowo", "David Gyasi", "Matt Damon", "William Devane"],
trailer: "http://youtube.com/watch?v=ePbKGoIGAXY",
url: "http://trakt.tv/movie/interstellar-2014",
tagline: "Mankind was born on Earth. It was never meant to die here.",
release_date: "1415347200"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "267964",
imdb_id: "",
genres : ["Action", "Animation", "Science Fiction"],
title: "Rakuen Tsuihou: Expelled From Paradise",
directors : ["Seiji Mizushima"],
actors : [],
trailer: "http://youtube.com/watch?v=5QPlxbdTfAE",
url: "http://trakt.tv/movie/rakuen-tsuihou-expelled-from-paradise-2014",
tagline: "",
release_date: "1416038400"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "100042",
imdb_id: "tt2096672",
genres : ["Comedy"],
title: "Dumb and Dumber To",
directors : ["Bobby Farrelly", "Peter Farrelly"],
actors : ["Jim Carrey", "Jeff Daniels", "Rachel Melvin", "Kathleen Turner", "Brady Bluhm", "Laurie Holden", "Steve Tom", "Rob Riggle", "Jennifer Lawrence", "Gregory Fears", "Eddie Shin", "Atkins Estimonds", "Lindsay Ayliffe", "Matthew Cardarople", "Tim Campione", "Jennifer Cocker", "Derrick Dean", "Garret H. Dumas", "Shelton Foreman", "Jeff Matthew Glover", "Walter Hendrix III", "Lauren Henneberg", "Michael Jaegers", "Aaron Kischnick", "Rob Koebel", "Taylor McPherson", "David Pascua", "William R. Phillips", "Josh Turner", "Stefan Walker Armstrong", "Walt Arnett", "Paul Bednarz", "Erika Bierman", "Derek Blankenship", "Kassidy Claire", "Jesse Clark", "Bryan Dilbeck", "Joe Foley", "Abigail Gamache", "Dalton E. Gray", "Llauryn P. Hendrix", "Ron Hudson", "Kathlene Huslin", "Erick Reihs Jackson", "Darien Johnson", "Jeffrey Karantza", "Debi Kimsey", "Anthony R. McClara", "Michael McCrudden", "Richard Melton", "Maia Moss-Fife", "Ryan Nesset", "Orbert Rogers", "Sade Shearer", "Dereck Smith", "Jeff Sumner", "Dave Walpole", "Christina Michelle Williams", "Brett Wyman", "Doris Dean", "John Deifer", "Jacklyn Edney", "David Emmett", "Cody Mark Hanna", "Billy Boy Johnson", "John Merical", "Barbara Prince"],
trailer: "http://youtube.com/watch?v=bIqvQFqPavA",
url: "http://trakt.tv/movie/dumb-and-dumber-to-2014",
tagline: "",
release_date: "1415952000"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "286532",
imdb_id: "tt0910885",
genres : [],
title: "A Merry Friggin' Christmas",
directors : ["Tristram Shapeero"],
actors : ["Robin Williams", "Lauren Graham", "Wendi McLendon-Covey", "Joel McHale", "Jeffrey Tambor", "Matt L. Jones", "Pierce Gagnon", "Candice Bergen", "Oliver Platt", "Clark Duke", "Amir Arison", "Ryan Lee", "Tim Heidecker", "Amara Miller", "Gene Jones", "Mark Proksch", "Bebe Wood", "Parisa Johnston", "Steele Gagnon", "Barak Hardley", "Karan Kendrick", "J.J. Jones", "Michael Shikany"],
trailer: "http://youtube.com/watch?v=TGkBu_qALpg",
url: "http://trakt.tv/movie/a-merry-friggin-christmas-2014",
tagline: "Spend it with the ones you loathe",
release_date: "1415347200"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "145221",
imdb_id: "tt1935302",
genres : [],
title: "Monsters: Dark Continent",
directors : ["Tom Green"],
actors : [],
trailer: "http://youtube.com/watch?v=2z40fisJWq8",
url: "http://trakt.tv/movie/monsters-dark-continent-2014",
tagline: "",
release_date: "1417161600"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "112454",
imdb_id: "tt1780798",
genres : [],
title: "Clown",
directors : ["Jon Watts"],
actors : ["Eli Roth", "Peter Stormare", "Laura Allen", "Elizabeth Whitmere", "Christian Distefano", "John MacDonald", "Chuck Shamata", "Andy Powers", "Sarah Scheffer", "Claudia Jurt", "Julia Long", "Matthew Stefiuk", "Robert Reynolds", "Allen Altman", "Brandon Stouffer", "Rachel Shugar", "Jodi Larratt", "Abigail Lieff", "Jocelyn Deighton", "Amy Balaton"],
trailer: "http://youtube.com/watch?v=utmvmr7cgcg",
url: "http://trakt.tv/movie/clown-2014",
tagline: "",
release_date: "1415865600"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "110416",
imdb_id: "tt1865505",
genres : ["Animation", "Fantasy", "Family"],
title: "Song of the Sea",
directors : ["Tomm Moore"],
actors : ["Brendan Gleeson", "Fionnula Flanagan", "David Rawle", "Pat Shortt", "Jon Kenny", "Lisa Hannigan"],
trailer: "http://youtube.com/watch?v=t0Ejpl3QFuU",
url: "http://trakt.tv/movie/song-of-the-sea-2014",
tagline: "",
release_date: "1418198400"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "298833",
imdb_id: "tt2173248",
genres : [],
title: "Blood Ransom",
directors : [],
actors : [],
trailer: "http://youtube.com/watch?v=5pqNnFpHf20",
url: "http://trakt.tv/movie/blood-ransom-2014",
tagline: "",
release_date: "1414738800"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "260001",
imdb_id: "tt2870808",
genres : ["Comedy", "Romance"],
title: "Life Partners",
directors : ["Susanna Fogel"],
actors : ["Leighton Meester", "Gillian Jacobs", "Gabourey Sidibe", "Adam Brody", "Mark Feuerstein", "Abby Elliott", "Kate McKinnon", "Greer Grammer"],
trailer: "http://youtube.com/watch?v=AgCPs6iKF2w",
url: "http://trakt.tv/movie/life-partners-2014",
tagline: "One guy can ruin the perfect relationship.",
release_date: "1417766400"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "245700",
imdb_id: "tt2473794",
genres : ["Drama"],
title: "Mr. Turner",
directors : ["Mike Leigh"],
actors : ["Timothy Spall", "Roger Ashton-Griffiths", "Jamie Thomas King", "Lesley Manville", "Lee Ingleby", "Richard Bremmer", "James Fleet", "Karina Fernandez"],
trailer: "http://youtube.com/watch?v=7GKlo2xWvuI",
url: "http://trakt.tv/movie/mr-turner-2014",
tagline: "",
release_date: "1418976000"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "239563",
imdb_id: "tt2170593",
genres : ["Comedy"],
title: "St. Vincent",
directors : ["Theodore Melfi"],
actors : ["Bill Murray", "Melissa McCarthy", "Naomi Watts", "Chris O'Dowd", "Terrence Howard", "Selenis Leyva", "Nathan Corddry", "Katharina Damm", "Scott Adsit", "Jaeden Lieberher", "Kimberly Quinn", "Lenny Venito", "Alyssa Ruland", "Alexandra Fong", "Greta Lee", "James Andrew O'Connor", "Casey Roberts", "Dario Barosso"],
trailer: "http://youtube.com/watch?v=BCJDuqLuPZA",
url: "http://trakt.tv/movie/st-vincent-2014",
tagline: "",
release_date: "1414738800"}).save(function(err, n) {});
