new UpcomingMovies({tmdb_id: "242512",
imdb_id: "tt1204977",
genres : ["Horror"],
title: "Ouija",
directors : ["Stiles White"],
actors : ["Olivia Cooke", "Ana Coto", "Daren Kagasoff", "Douglas Smith", "Vivis Colombetti", "Bianca Santos", "Erin Moriarty", "Shelley Hennig"],
trailer: "http://youtube.com/watch?v=xBLmBdn2QF8",
url: "http://trakt.tv/movie/ouija-2014",
tagline: "Keep telling yourself it's just a game",
release_date: "1414134000"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "245891",
imdb_id: "tt2911666",
genres : ["Action", "Thriller"],
title: "John Wick",
directors : ["Chad Stahelski", "David Leitch"],
actors : ["Keanu Reeves", "Adrianne Palicki", "Bridget Regan", "Willem Dafoe", "Bridget Moynahan", "Jason Isaacs", "Alfie Allen", "Omer Barnea", "Lance Reddick", "Toby Leonard Moore"],
trailer: "http://youtube.com/watch?v=RllJtOw0USI",
url: "http://trakt.tv/movie/john-wick-2014",
tagline: "Don't set him off.",
release_date: "1414134000"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "177572",
imdb_id: "tt2245084",
genres : ["Action", "Animation", "Comedy", "Science Fiction", "Family"],
title: "Big Hero 6",
directors : ["Chris Williams", "Don Hall"],
actors : ["Jamie Chung", "T.J. Miller", "Maya Rudolph"],
trailer: "http://youtube.com/watch?v=QA9tb_5kMF0",
url: "http://trakt.tv/movie/big-hero-6-2014",
tagline: "",
release_date: "1415347200"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "266856",
imdb_id: "tt2980516",
genres : ["Drama"],
title: "The Theory of Everything",
directors : ["James Marsh"],
actors : ["Felicity Jones", "Emily Watson", "Harry Lloyd", "David Thewlis", "Charlotte Hope", "Adam Godley", "Lesley Manville", "Maxine Peake", "Eddie Redmayne"],
trailer: "http://youtube.com/watch?v=1YjF5gV_Tc4",
url: "http://trakt.tv/movie/the-theory-of-everything-2014",
tagline: "",
release_date: "1415347200"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "289416",
imdb_id: "tt3068192",
genres : ["Horror", "Thriller"],
title: "Grace: The Possession",
directors : ["Jeff Chan"],
actors : ["Alexia Fast", "Joel Moore", "Lin Shaye", "Brett Dier", "John Emmett Tracy", "Daniel Arnold"],
trailer: "http://youtube.com/watch?v=ijkk9itwpsQ",
url: "http://trakt.tv/movie/grace-the-possession-2014",
tagline: "Innocence ends in blood",
release_date: "1414479600"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "239563",
imdb_id: "tt2170593",
genres : ["Comedy"],
title: "St. Vincent",
directors : ["Theodore Melfi"],
actors : ["Bill Murray", "Melissa McCarthy", "Naomi Watts", "Chris O'Dowd", "Terrence Howard", "Selenis Leyva", "Nathan Corddry", "Katharina Damm", "Scott Adsit", "Jaeden Lieberher", "Kimberly Quinn", "Lenny Venito", "Alyssa Ruland", "Alexandra Fong", "Greta Lee", "James Andrew O'Connor", "Casey Roberts", "Dario Barosso"],
trailer: "http://youtube.com/watch?v=BCJDuqLuPZA",
url: "http://trakt.tv/movie/st-vincent-2014",
tagline: "",
release_date: "1414738800"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "286532",
imdb_id: "tt0910885",
genres : [],
title: "A Merry Friggin' Christmas",
directors : ["Tristram Shapeero"],
actors : ["Robin Williams", "Lauren Graham", "Wendi McLendon-Covey", "Joel McHale", "Jeffrey Tambor", "Matt L. Jones", "Pierce Gagnon", "Candice Bergen", "Oliver Platt", "Clark Duke", "Amir Arison", "Ryan Lee", "Tim Heidecker", "Amara Miller", "Gene Jones", "Mark Proksch", "Bebe Wood", "Parisa Johnston", "Steele Gagnon", "Barak Hardley", "Karan Kendrick", "J.J. Jones", "Michael Shikany"],
trailer: "http://youtube.com/watch?v=TGkBu_qALpg",
url: "http://trakt.tv/movie/a-merry-friggin-christmas-2014",
tagline: "Spend it with the ones you loathe",
release_date: "1415347200"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "157841",
imdb_id: "tt1981107",
genres : ["Adventure"],
title: "The Young and Prodigious T.S. Spivet",
directors : ["Jean-Pierre Jeunet"],
actors : ["Kyle Catlett", "Helena Bonham Carter", "Judy Davis", "Callum Keith Rennie", "Niamh Wilson", "Jakob Davies", "Rick Mercer", "Robert Maillet", "Julian Richings", "Dominique Pinon", "Dawn Ford", "Lisa Bronwyn Moore"],
trailer: "http://youtube.com/watch?v=wjOYX_a8GXw",
url: "http://trakt.tv/movie/the-young-and-prodigious-ts-spivet-2014",
tagline: "",
release_date: "1414306800"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "242582",
imdb_id: "tt2872718",
genres : ["Crime", "Drama", "Thriller"],
title: "Nightcrawler",
directors : ["Dan Gilroy"],
actors : ["Jake Gyllenhaal", "Bill Paxton", "Rene Russo", "Kevin Rahm", "Riz Ahmed", "Kathleen York", "Ann Cusack"],
trailer: "http://youtube.com/watch?v=1lEdwqwOttg",
url: "http://trakt.tv/movie/nightcrawler-2014",
tagline: "The City Shines Brightest at Night",
release_date: "1414738800"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "157336",
imdb_id: "tt0816692",
genres : ["Science Fiction", "Drama"],
title: "Interstellar",
directors : ["Christopher Nolan"],
actors : ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain", "Michael Caine", "Casey Affleck", "Ellen Burstyn", "Timothee Chalamet", "Mackenzie Foy", "John Lithgow", "Bill Irwin", "Topher Grace", "Wes Bentley", "David Oyelowo", "David Gyasi", "Matt Damon", "William Devane"],
trailer: "http://youtube.com/watch?v=ePbKGoIGAXY",
url: "http://trakt.tv/movie/interstellar-2014",
tagline: "Mankind was born on Earth. It was never meant to die here.",
release_date: "1415347200"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "273881",
imdb_id: "tt3744464",
genres : ["Action", "Adventure", "Science Fiction"],
title: "Space Sheriff Shaider: THE NEXT GENERATION",
directors : [],
actors : [],
trailer: "http://youtube.com/watch?v=Ykzl6rU0v-I",
url: "http://trakt.tv/movie/space-sheriff-shaider-the-next-generation-2014",
tagline: "",
release_date: "1415347200"}).save(function(err, n) {});
new UpcomingMovies({tmdb_id: "299739",
imdb_id: "tt2245172",
genres : [],
title: "Real Heroes",
directors : [],
actors : [],
trailer: "http://youtube.com/watch?v=5Bwl0kAb7AY",
url: "http://trakt.tv/movie/real-heroes-2014",
tagline: "",
release_date: "1415347200"}).save(function(err, n) {});
